/*******************************************************************************
 * AbyssalCraft
 * Copyright (c) 2012 - 2022 Shinoow.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser Public License v3
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-3.0.txt
 * 
 * Contributors:
 *     Shinoow -  implementation
 ******************************************************************************/
package com.shinoow.abyssalcraft.init;

import com.shinoow.abyssalcraft.AbyssalCraft;
import com.shinoow.abyssalcraft.api.biome.IDarklandsBiome;
import com.shinoow.abyssalcraft.api.block.ACBlocks;
import com.shinoow.abyssalcraft.api.item.IUnlockableItem;
import com.shinoow.abyssalcraft.api.necronomicon.condition.*;
import com.shinoow.abyssalcraft.common.blocks.*;
import com.shinoow.abyssalcraft.common.blocks.BlockACBrick.EnumBrickType;
import com.shinoow.abyssalcraft.common.blocks.BlockACCobblestone.EnumCobblestoneType;
import com.shinoow.abyssalcraft.common.blocks.BlockACStone.EnumStoneType;
import com.shinoow.abyssalcraft.common.blocks.BlockCrystalCluster.EnumCrystalType;
import com.shinoow.abyssalcraft.common.blocks.BlockCrystalCluster.EnumCrystalType2;
import com.shinoow.abyssalcraft.common.blocks.BlockRitualAltar.EnumRitualMatType;
import com.shinoow.abyssalcraft.common.blocks.BlockStatue.EnumDeityType;
import com.shinoow.abyssalcraft.common.blocks.BlockTieredEnergyPedestal.EnumDimType;
import com.shinoow.abyssalcraft.common.blocks.IngotBlock.EnumIngotType;
import com.shinoow.abyssalcraft.common.blocks.itemblock.*;
import com.shinoow.abyssalcraft.common.blocks.tile.*;
import com.shinoow.abyssalcraft.common.world.gen.WorldGenDLT;
import com.shinoow.abyssalcraft.common.world.gen.WorldGenDrT;
import com.shinoow.abyssalcraft.lib.ACLib;
import com.shinoow.abyssalcraft.lib.ACTabs;

import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.MapColor;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.event.*;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class BlockHandler implements ILifeCycleHandler {

	public static Block Darkbrickslab2, Darkcobbleslab2, abyslab2, Darkstoneslab2, DLTslab2,
	Altar, dreadbrickslab2, abydreadbrickslab2, cstonebrickslab2, ethaxiumslab2, house,
	darkethaxiumslab2, abycobbleslab2, dreadcobbleslab2, abydreadcobbleslab2, cstonecobbleslab2;

	@Override
	public void preInit(FMLPreInitializationEvent event) {
		ACBlocks.darkstone = new BlockACStone(EnumStoneType.DARKSTONE).setTranslationKey("darkstone");
		ACBlocks.abyssal_stone = new BlockACStone(EnumStoneType.ABYSSAL_STONE).setTranslationKey("abystone");
		ACBlocks.dreadstone = new BlockACStone(EnumStoneType.DREADSTONE).setTranslationKey("dreadstone");
		ACBlocks.abyssalnite_stone = new BlockACStone(EnumStoneType.ABYSSALNITE_STONE).setTranslationKey("abydreadstone");
		ACBlocks.coralium_stone = new BlockACStone(EnumStoneType.CORALIUM_STONE).setTickRandomly(true).setTranslationKey("cstone");
		ACBlocks.ethaxium = new BlockACStone(EnumStoneType.ETHAXIUM).setTranslationKey("ethaxium");
		ACBlocks.omothol_stone = new BlockACStone(EnumStoneType.OMOTHOL_STONE).setTranslationKey("omotholstone");
		ACBlocks.monolith_stone = new BlockACStone(EnumStoneType.MONOLITH_STONE).setTranslationKey("monolithstone");
		ACBlocks.darkstone_brick = new BlockACBrick(1.65F, 12.0F, MapColor.BLACK).setTranslationKey("darkstone_brick");
		ACBlocks.chiseled_darkstone_brick = new BlockACBrick(1.65F, 12.0F, MapColor.BLACK).remap("darkstone_brick", EnumBrickType.CHISELED).setTranslationKey("chiseled_darkstone_brick");
		ACBlocks.cracked_darkstone_brick = new BlockACBrick(1.65F, 12.0F, MapColor.BLACK).remap("darkstone_brick", EnumBrickType.CRACKED).setTranslationKey("cracked_darkstone_brick");
		ACBlocks.darkstone_cobblestone = new BlockACCobblestone(EnumCobblestoneType.DARKSTONE).setTranslationKey("darkstone_cobble");
		ACBlocks.abyssal_cobblestone = new BlockACCobblestone(EnumCobblestoneType.ABYSSAL_STONE).setTranslationKey("abyssalcobblestone");
		ACBlocks.dreadstone_cobblestone = new BlockACCobblestone(EnumCobblestoneType.DREADSTONE).setTranslationKey("dreadstonecobblestone");
		ACBlocks.abyssalnite_cobblestone = new BlockACCobblestone(EnumCobblestoneType.ABYSSALNITE_STONE).setTranslationKey("abyssalnitecobblestone");
		ACBlocks.coralium_cobblestone = new BlockACCobblestone(EnumCobblestoneType.CORALIUM_STONE).setTranslationKey("coraliumcobblestone");
		ACBlocks.glowing_darkstone_bricks = new BlockACBasic(Material.ROCK, "pickaxe", 3, 55F, 3000F, SoundType.STONE, MapColor.BLACK).setLightLevel(1.0F).setTranslationKey("dsglow");
		ACBlocks.darkstone_brick_slab = new BlockACSingleSlab(Material.ROCK, SoundType.STONE, MapColor.BLACK).setHardness(1.65F).setResistance(12.0F).setTranslationKey("darkbrickslab1");
		Darkbrickslab2 = new BlockACDoubleSlab(ACBlocks.darkstone_brick_slab, Material.ROCK).setHardness(1.65F).setResistance(12.0F).setTranslationKey("darkbrickslab2");
		ACBlocks.darkstone_cobblestone_slab = new BlockACSingleSlab(Material.ROCK, SoundType.STONE, MapColor.BLACK).setHardness(1.65F) .setResistance(12.0F).setTranslationKey("darkcobbleslab1");
		Darkcobbleslab2 = new BlockACDoubleSlab(ACBlocks.darkstone_cobblestone_slab, Material.ROCK).setHardness(1.65F) .setResistance(12.0F).setTranslationKey("darkcobbleslab2");
		ACBlocks.darkstone_brick_stairs = new BlockACStairs(ACBlocks.darkstone_brick).setHardness(1.65F).setResistance(12.0F).setTranslationKey("dbstairs");
		ACBlocks.darkstone_cobblestone_stairs = new BlockACStairs(ACBlocks.darkstone_cobblestone).setHardness(1.65F).setResistance(12.0F).setTranslationKey("dcstairs");
		ACBlocks.darklands_oak_sapling = new BlockACSapling(new WorldGenDLT(true)).setHardness(0.0F).setResistance(0.0F).setTranslationKey("dltsapling");
		ACBlocks.darklands_oak_leaves = new BlockACLeaves(ACBlocks.darklands_oak_sapling, MapColor.BLUE).setHardness(0.2F).setResistance(1.0F).setTranslationKey("dltleaves");
		ACBlocks.darklands_oak_wood = new BlockACLog(MapColor.BROWN).setHardness(2.0F).setResistance(1.0F).setTranslationKey("dltlog");
		ACBlocks.darklands_oak_wood_2 = new BlockACLog(MapColor.BROWN).setHardness(2.0F).setResistance(1.0F).setTranslationKey("dltlog");
		ACBlocks.abyssal_stone_brick = new BlockACBrick(2, 1.8F, 12.0F, MapColor.GREEN).setTranslationKey("abybrick");
		ACBlocks.chiseled_abyssal_stone_brick = new BlockACBrick(2, 1.8F, 12.0F, MapColor.GREEN).remap("abybrick", EnumBrickType.CHISELED).setTranslationKey("chiseled_abyssal_stone_brick");
		ACBlocks.cracked_abyssal_stone_brick = new BlockACBrick(2, 1.8F, 12.0F, MapColor.GREEN).remap("abybrick", EnumBrickType.CRACKED).setTranslationKey("cracked_abyssal_stone_brick");
		ACBlocks.abyssal_stone_brick_slab = new BlockACSingleSlab(Material.ROCK, "pickaxe", 2, SoundType.STONE, MapColor.GREEN).setCreativeTab(ACTabs.tabBlock).setHardness(1.8F).setResistance(12.0F).setTranslationKey("abyslab1");
		abyslab2 = new BlockACDoubleSlab(ACBlocks.abyssal_stone_brick_slab, Material.ROCK, "pickaxe", 2).setHardness(1.8F).setResistance(12.0F).setTranslationKey("abyslab2");
		ACBlocks.abyssal_stone_brick_stairs = new BlockACStairs(ACBlocks.abyssal_stone_brick, "pickaxe", 2).setHardness(1.65F).setResistance(12.0F).setTranslationKey("abystairs");
		ACBlocks.coralium_ore = new BlockACOre(2, 3.0F, 6.0F).setTranslationKey("coraliumore");
		ACBlocks.abyssalnite_ore = new BlockACOre(2, 3.0F, 6.0F).setTranslationKey("abyore");
		ACBlocks.abyssal_stone_brick_fence = new BlockACFence(Material.ROCK, "pickaxe", 2, SoundType.STONE, MapColor.GREEN).setHardness(1.8F).setResistance(12.0F).setTranslationKey("abyfence");
		ACBlocks.darkstone_cobblestone_wall = new BlockACWall(ACBlocks.darkstone_cobblestone).setHardness(1.65F).setResistance(12.0F).setTranslationKey("dscwall");
		ACBlocks.wooden_crate = new BlockCrate().setHardness(3.0F).setResistance(6.0F).setTranslationKey("woodencrate");
		ACBlocks.oblivion_deathbomb = new BlockODB().setHardness(3.0F).setResistance(0F).setTranslationKey("odb");
		ACBlocks.block_of_abyssalnite = new IngotBlock(EnumIngotType.ABYSSALNITE).setTranslationKey("abyblock");
		ACBlocks.block_of_refined_coralium = new IngotBlock(EnumIngotType.REFINED_CORALIUM).setTranslationKey("corblock");
		ACBlocks.block_of_dreadium = new IngotBlock(EnumIngotType.DREADIUM).setTranslationKey("dreadiumblock");
		ACBlocks.block_of_ethaxium = new IngotBlock(EnumIngotType.ETHAXIUM).setTranslationKey("ethaxiumblock");
		ACBlocks.coralium_infused_stone = new BlockACOre(3, 3.0F, 6.0F).setTranslationKey("coraliumstone");
		ACBlocks.odb_core = new BlockODBcore().setHardness(3.0F).setResistance(0F).setTranslationKey("odbcore");
		ACBlocks.darkstone_slab = new BlockACSingleSlab(Material.ROCK, SoundType.STONE, MapColor.BLACK).setCreativeTab(ACTabs.tabBlock).setHardness(1.65F).setResistance(12.0F).setTranslationKey("darkstoneslab1");
		Darkstoneslab2 = new BlockACDoubleSlab(ACBlocks.darkstone_slab, Material.ROCK).setHardness(1.65F).setResistance(12.0F).setTranslationKey("darkstoneslab2");
		ACBlocks.darkstone_button = new BlockACButton(true, "DS").setHardness(0.6F).setResistance(12.0F).setTranslationKey("dsbutton");
		ACBlocks.darkstone_pressure_plate = new BlockACPressureplate("DS", Material.ROCK, BlockACPressureplate.Sensitivity.MOBS, SoundType.STONE).setHardness(0.6F).setResistance(12.0F).setTranslationKey("dspplate");
		ACBlocks.darklands_oak_planks = new BlockACBasic(Material.WOOD, 2.0F, 5.0F, SoundType.WOOD, MapColor.BROWN).setTranslationKey("dltplank");
		ACBlocks.darklands_oak_button = new BlockACButton(true, "DLTplank").setHardness(0.5F).setTranslationKey("dltbutton");
		ACBlocks.darklands_oak_pressure_plate = new BlockACPressureplate("DLTplank", Material.WOOD, BlockACPressureplate.Sensitivity.EVERYTHING, SoundType.WOOD).setHardness(0.5F).setTranslationKey("dltpplate");
		ACBlocks.darklands_oak_stairs = new BlockACStairs(ACBlocks.darklands_oak_planks).setHardness(2.0F).setResistance(5.0F).setTranslationKey("dltstairs");
		ACBlocks.darklands_oak_slab = new BlockACSingleSlab(Material.WOOD, SoundType.WOOD, MapColor.BROWN).setHardness(2.0F).setResistance(5.0F).setTranslationKey("dltslab1");
		DLTslab2 = new BlockACDoubleSlab(ACBlocks.darklands_oak_slab, Material.WOOD).setHardness(2.0F).setResistance(5.0F).setTranslationKey("dltslab2");
		ACBlocks.dreadlands_infused_powerstone = new BlockPSDL().setHardness(50.0F).setResistance(3000F).setCreativeTab(ACTabs.tabDecoration).setTranslationKey("psdl");
		ACBlocks.abyssal_coralium_ore = new BlockACOre(3, 3.0F, 6.0F).setTranslationKey("abycorore");
		Altar = new BlockAltar().setHardness(4.0F).setResistance(300.0F).setTranslationKey("altar");
		ACBlocks.abyssal_stone_button = new BlockACButton(false, "pickaxe", 2, "AS").setHardness(0.8F).setResistance(12.0F).setTranslationKey("abybutton");
		ACBlocks.abyssal_stone_pressure_plate = new BlockACPressureplate("AS", Material.ROCK, BlockACPressureplate.Sensitivity.MOBS, "pickaxe", 2, SoundType.STONE).setHardness(0.8F).setResistance(12.0F).setTranslationKey("abypplate");
		ACBlocks.darkstone_brick_fence = new BlockACFence(Material.ROCK, SoundType.STONE, MapColor.BLACK).setHardness(1.65F).setResistance(12.0F).setTranslationKey("dsbfence");
		ACBlocks.darklands_oak_fence = new BlockACFence(Material.WOOD, SoundType.WOOD, MapColor.BROWN).setHardness(2.0F).setResistance(5.0F).setTranslationKey("dltfence");
		ACBlocks.dreaded_abyssalnite_ore = new BlockACOre(4, 2.5F, 20.0F).setTranslationKey("dreadore");
		ACBlocks.dreadlands_abyssalnite_ore = new BlockACOre(4, 2.5F, 20.0F).setTranslationKey("abydreadore");
		ACBlocks.dreadstone_brick = new BlockACBrick(4, 2.5F, 20.0F, MapColor.RED).setTranslationKey("dreadbrick");
		ACBlocks.chiseled_dreadstone_brick = new BlockACBrick(4, 2.5F, 20.0F, MapColor.RED).remap("dreadbrick", EnumBrickType.CHISELED).setTranslationKey("chiseled_dreadstone_brick");
		ACBlocks.cracked_dreadstone_brick = new BlockACBrick(4, 2.5F, 20.0F, MapColor.RED).remap("dreadbrick", EnumBrickType.CRACKED).setTranslationKey("cracked_dreadstone_brick");
		ACBlocks.abyssalnite_stone_brick = new BlockACBrick(4, 2.5F, 20.0F, MapColor.PURPLE).setTranslationKey("abydreadbrick");
		ACBlocks.chiseled_abyssalnite_stone_brick = new BlockACBrick(4, 2.5F, 20.0F, MapColor.PURPLE).remap("abydreadstone", EnumBrickType.CHISELED).setTranslationKey("chiseled_abyssalnite_stone_brick");
		ACBlocks.cracked_abyssalnite_stone_brick = new BlockACBrick(4, 2.5F, 20.0F, MapColor.PURPLE).remap("abydreadbrick", EnumBrickType.CRACKED).setTranslationKey("cracked_abyssalnite_stone_brick");
		ACBlocks.dreadlands_sapling = new BlockACSapling(new WorldGenDrT(true)).setHardness(0.0F).setResistance(0.0F).setTranslationKey("dreadsapling");
		ACBlocks.dreadlands_log = new BlockACLog(MapColor.RED).setHardness(2.0F).setResistance(12.0F).setTranslationKey("dreadlog");
		ACBlocks.dreadlands_leaves = new BlockACLeaves(ACBlocks.dreadlands_sapling, MapColor.RED).setHardness(0.2F).setResistance(1.0F).setTranslationKey("dreadleaves");
		ACBlocks.dreadlands_planks = new BlockACBasic(Material.WOOD, 2.0F, 5.0F, SoundType.WOOD, MapColor.RED).setTranslationKey("dreadplanks");
		ACBlocks.depths_ghoul_head = new BlockDGhead().setTranslationKey("dghead");
		ACBlocks.liquid_coralium = new BlockCLiquid().setResistance(500.0F).setLightLevel(1.0F).setTranslationKey("cwater");
		ACBlocks.dreadlands_grass = new BlockDreadGrass().setHardness(0.4F).setTranslationKey("dreadgrass");
		ACBlocks.pete_head = new BlockDGhead().setTranslationKey("phead");
		ACBlocks.mr_wilson_head = new BlockDGhead().setTranslationKey("whead");
		ACBlocks.dr_orange_head = new BlockDGhead().setTranslationKey("ohead");
		ACBlocks.dreadstone_brick_stairs = new BlockACStairs(ACBlocks.dreadstone_brick, "pickaxe", 4).setHardness(2.5F).setResistance(20.0F).setTranslationKey("dreadbrickstairs");
		ACBlocks.dreadstone_brick_fence = new BlockACFence(Material.ROCK, "pickaxe", 4, SoundType.STONE, MapColor.RED).setHardness(2.5F).setResistance(20.0F).setTranslationKey("dreadbrickfence");
		ACBlocks.dreadstone_brick_slab = new BlockACSingleSlab(Material.ROCK, "pickaxe", 4, SoundType.STONE, MapColor.RED).setHardness(2.5F).setResistance(20.0F).setTranslationKey("dreadbrickslab1");
		dreadbrickslab2 = new BlockACDoubleSlab(ACBlocks.dreadstone_brick_slab, Material.ROCK, "pickaxe", 4).setHardness(2.5F).setResistance(20.0F).setTranslationKey("dreadbrickslab2");
		ACBlocks.abyssalnite_stone_brick_stairs = new BlockACStairs(ACBlocks.abyssalnite_stone_brick, "pickaxe", 4).setHardness(2.5F).setResistance(20.0F).setTranslationKey("abydreadbrickstairs");
		ACBlocks.abyssalnite_stone_brick_fence = new BlockACFence(Material.ROCK, "pickaxe", 4, SoundType.STONE, MapColor.PURPLE).setHardness(2.5F).setResistance(20.0F).setTranslationKey("abydreadbrickfence");
		ACBlocks.abyssalnite_stone_brick_slab = new BlockACSingleSlab(Material.ROCK, "pickaxe", 4, SoundType.STONE, MapColor.PURPLE).setHardness(2.5F).setResistance(20.0F).setTranslationKey("abydreadbrickslab1");
		abydreadbrickslab2 = new BlockACDoubleSlab(ACBlocks.abyssalnite_stone_brick_slab, Material.ROCK, "pickaxe", 4).setHardness(2.5F).setResistance(20.0F).setTranslationKey("abydreadbrickslab2");
		ACBlocks.liquid_antimatter = new BlockAntiliquid().setResistance(500.0F).setLightLevel(0.5F).setTranslationKey("antiwater");
		ACBlocks.coralium_stone_brick = new BlockACBrick(1.5F, 10.0F, MapColor.CYAN).setTranslationKey("cstonebrick");
		ACBlocks.chiseled_coralium_stone_brick = new BlockACBrick(1.5F, 10.0F, MapColor.CYAN).remap("cstonebrick", EnumBrickType.CHISELED).setTranslationKey("chiseled_coralium_stone_brick");
		ACBlocks.cracked_coralium_stone_brick = new BlockACBrick(1.5F, 10.0F, MapColor.CYAN).remap("cstonebrick", EnumBrickType.CRACKED).setTranslationKey("cracked_coralium_stone_brick");
		ACBlocks.coralium_stone_brick_fence = new BlockACFence(Material.ROCK, SoundType.STONE, MapColor.CYAN).setHardness(1.5F).setResistance(10.0F).setTranslationKey("cstonebrickfence");
		ACBlocks.coralium_stone_brick_slab = new BlockACSingleSlab(Material.ROCK, SoundType.STONE, MapColor.CYAN).setHardness(1.5F).setResistance(10.0F).setTranslationKey("cstonebrickslab1");
		cstonebrickslab2 = new BlockACDoubleSlab(ACBlocks.coralium_stone_brick_slab, Material.ROCK).setHardness(1.5F).setResistance(10.0F).setTranslationKey("cstonebrickslab2");
		ACBlocks.coralium_stone_brick_stairs = new BlockACStairs(ACBlocks.coralium_stone_brick, "pickaxe", 0).setHardness(1.5F).setResistance(10.0F).setTranslationKey("cstonebrickstairs");
		ACBlocks.coralium_stone_button = new BlockACButton(false, "cstone").setHardness(0.6F).setResistance(12.0F).setTranslationKey("cstonebutton");
		ACBlocks.coralium_stone_pressure_plate = new BlockACPressureplate("cstone", Material.ROCK, BlockACPressureplate.Sensitivity.MOBS, SoundType.STONE).setHardness(0.6F).setResistance(12.0F).setTranslationKey("cstonepplate");
		ACBlocks.chagaroth_altar_top = new BlockDreadAltarTop().setHardness(30.0F).setResistance(300.0F).setCreativeTab(ACTabs.tabDecoration).setTranslationKey("dreadaltartop");
		ACBlocks.chagaroth_altar_bottom = new BlockDreadAltarBottom().setHardness(30.0F).setResistance(300.0F).setCreativeTab(ACTabs.tabDecoration).setTranslationKey("dreadaltarbottom");
		ACBlocks.crystallizer_idle = new BlockCrystallizer(false).setHardness(2.5F).setResistance(12.0F).setTranslationKey("crystallizer");
		ACBlocks.crystallizer_active = new BlockCrystallizer(true).setHardness(2.5F).setResistance(12.0F).setLightLevel(0.875F).setTranslationKey("crystallizer_on");
		ACBlocks.transmutator_idle = new BlockTransmutator(false).setHardness(2.5F).setResistance(12.0F).setTranslationKey("transmutator");
		ACBlocks.transmutator_active = new BlockTransmutator(true).setHardness(2.5F).setResistance(12.0F).setLightLevel(0.875F).setTranslationKey("transmutator_on");
		ACBlocks.dreadguard_spawner = new BlockSingleMobSpawner().setTranslationKey("dreadguardspawner");
		ACBlocks.chagaroth_spawner = new BlockSingleMobSpawner().setTranslationKey("chagarothspawner");
		ACBlocks.dreadlands_wood_fence = new BlockACFence(Material.WOOD, SoundType.WOOD, MapColor.RED).setHardness(2.0F).setResistance(5.0F).setTranslationKey("drtfence");
		ACBlocks.nitre_ore = new BlockACOre(2, 3.0F, 6.0F).setTranslationKey("nitreore");
		ACBlocks.abyssal_iron_ore = new BlockACOre(2, 3.0F, 6.0F).setTranslationKey("abyiroore");
		ACBlocks.abyssal_gold_ore = new BlockACOre(2, 5.0F, 10.0F).setTranslationKey("abygolore");
		ACBlocks.abyssal_diamond_ore = new BlockACOre(2, 5.0F, 10.0F).setTranslationKey("abydiaore");
		ACBlocks.abyssal_nitre_ore = new BlockACOre(2, 3.0F, 6.0F).setTranslationKey("abynitore");
		ACBlocks.abyssal_tin_ore = new BlockACOre(2, 3.0F, 6.0F).setTranslationKey("abytinore");
		ACBlocks.abyssal_copper_ore = new BlockACOre(2, 3.0F, 6.0F).setTranslationKey("abycopore");
		ACBlocks.pearlescent_coralium_ore = new BlockACOre(5, 8.0F, 10.0F).setTranslationKey("abypcorore");
		ACBlocks.liquified_coralium_ore = new BlockACOre(4, 10.0F, 12.0F).setTranslationKey("abylcorore");
		ACBlocks.solid_lava = new BlockSolidLava("solidlava");
		ACBlocks.ethaxium_brick = new BlockACBrick(8, 100.0F, Float.MAX_VALUE, MapColor.CLOTH).setTranslationKey("ethaxiumbrick");
		ACBlocks.chiseled_ethaxium_brick = new BlockACBrick(8, 100.0F, Float.MAX_VALUE, MapColor.CLOTH).remap("ethaxiumbrick", EnumBrickType.CHISELED).setTranslationKey("chiseled_ethaxium_brick");
		ACBlocks.cracked_ethaxium_brick = new BlockACBrick(8, 100.0F, Float.MAX_VALUE, MapColor.CLOTH).remap("ethaxiumbrick", EnumBrickType.CRACKED).setTranslationKey("cracked_ethaxium_brick");
		ACBlocks.ethaxium_pillar = new BlockEthaxiumPillar(100.0F, MapColor.CLOTH).setTranslationKey("ethaxiumpillar");
		ACBlocks.ethaxium_brick_stairs = new BlockACStairs(ACBlocks.ethaxium_brick, "pickaxe", 8).setHardness(100.0F).setResistance(Float.MAX_VALUE).setTranslationKey("ethaxiumbrickstairs");
		ACBlocks.ethaxium_brick_slab = new BlockACSingleSlab(Material.ROCK, "pickaxe", 8, SoundType.STONE, MapColor.CLOTH).setHardness(100.0F).setResistance(Float.MAX_VALUE).setTranslationKey("ethaxiumbrickslab1");
		ethaxiumslab2 = new BlockACDoubleSlab(ACBlocks.ethaxium_brick_slab, Material.ROCK, "pickaxe", 8).setHardness(100.0F).setResistance(Float.MAX_VALUE).setTranslationKey("ethaxiumbrickslab2");
		ACBlocks.ethaxium_brick_fence = new BlockACFence(Material.ROCK, "pickaxe", 8, SoundType.STONE, MapColor.CLOTH).setHardness(100.0F).setResistance(Float.MAX_VALUE).setTranslationKey("ethaxiumfence");
		ACBlocks.engraver = new BlockEngraver().setHardness(2.5F).setResistance(12.0F).setTranslationKey("engraver");
		house = new BlockHouse().setHardness(1.0F).setResistance(Float.MAX_VALUE).setTranslationKey("engraver_on");
		ACBlocks.materializer = new BlockMaterializer().setTranslationKey("materializer");
		ACBlocks.dark_ethaxium_brick = new BlockACBrick(8, 150.0F, Float.MAX_VALUE).setTranslationKey("darkethaxiumbrick");
		ACBlocks.chiseled_dark_ethaxium_brick = new BlockACBrick(8, 150.0F, Float.MAX_VALUE).remap("darkethaxiumbrick", EnumBrickType.CHISELED).setTranslationKey("chiseled_dark_ethaxium_brick");
		ACBlocks.cracked_dark_ethaxium_brick = new BlockACBrick(8, 150.0F, Float.MAX_VALUE).remap("darkethaxiumbrick", EnumBrickType.CRACKED).setTranslationKey("cracked_dark_ethaxium_brick");
		ACBlocks.dark_ethaxium_pillar = new BlockEthaxiumPillar(150.0F, MapColor.STONE).setTranslationKey("darkethaxiumpillar");
		ACBlocks.dark_ethaxium_brick_stairs = new BlockACStairs(ACBlocks.dark_ethaxium_brick, "pickaxe", 8).setHardness(150.0F).setResistance(Float.MAX_VALUE).setTranslationKey("darkethaxiumbrickstairs");
		ACBlocks.dark_ethaxium_brick_slab = new BlockACSingleSlab(Material.ROCK, "pickaxe", 8, SoundType.STONE).setHardness(150.0F).setResistance(Float.MAX_VALUE).setTranslationKey("darkethaxiumbrickslab1");
		darkethaxiumslab2 = new BlockACDoubleSlab(ACBlocks.dark_ethaxium_brick_slab, Material.ROCK, "pickaxe", 8).setHardness(150.0F).setResistance(Float.MAX_VALUE).setTranslationKey("darkethaxiumbrickslab2");
		ACBlocks.dark_ethaxium_brick_fence = new BlockACFence(Material.ROCK, "pickaxe", 8, SoundType.STONE, MapColor.STONE).setHardness(150.0F).setResistance(Float.MAX_VALUE).setTranslationKey("darkethaxiumbrickfence");
		ACBlocks.ritual_altar_stone = new BlockRitualAltar(() -> Blocks.COBBLESTONE.getDefaultState(), 0, EnumRitualMatType.COBBLESTONE).setTranslationKey("ritualaltar");
		ACBlocks.ritual_altar_darkstone = new BlockRitualAltar(() -> ACBlocks.darkstone_cobblestone.getDefaultState(), 0, EnumRitualMatType.DARKSTONE_COBBLESTONE).setTranslationKey("ritualaltar");
		ACBlocks.ritual_altar_abyssal_stone = new BlockRitualAltar(() -> ACBlocks.abyssal_cobblestone.getDefaultState(), 1, EnumRitualMatType.ABYSSAL_STONE_BRICK).setTranslationKey("ritualaltar");
		ACBlocks.ritual_altar_coralium_stone = new BlockRitualAltar(() -> ACBlocks.coralium_cobblestone.getDefaultState(), 1, EnumRitualMatType.CORALIUM_STONE_BRICK).setTranslationKey("ritualaltar");
		ACBlocks.ritual_altar_dreadstone = new BlockRitualAltar(() -> ACBlocks.dreadstone_cobblestone.getDefaultState(), 2, EnumRitualMatType.DREADSTONE_BRICK).setTranslationKey("ritualaltar");
		ACBlocks.ritual_altar_abyssalnite_stone = new BlockRitualAltar(() -> ACBlocks.abyssalnite_cobblestone.getDefaultState(), 2, EnumRitualMatType.ABYSSALNITE_STONE_BRICK).setTranslationKey("ritualaltar");
		ACBlocks.ritual_altar_ethaxium = new BlockRitualAltar(() -> ACBlocks.ethaxium_brick.getDefaultState(), 3, EnumRitualMatType.ETHAXIUM_BRICK).setTranslationKey("ritualaltar");
		ACBlocks.ritual_altar_dark_ethaxium = new BlockRitualAltar(() -> ACBlocks.dark_ethaxium_brick.getDefaultState(), 3, EnumRitualMatType.DARK_ETHAXIUM_BRICK).setTranslationKey("ritualaltar");
		ACBlocks.ritual_pedestal_stone = new BlockRitualPedestal(() -> Blocks.COBBLESTONE.getDefaultState(), 0, EnumRitualMatType.COBBLESTONE).setTranslationKey("ritualpedestal");
		ACBlocks.ritual_pedestal_darkstone = new BlockRitualPedestal(() -> ACBlocks.darkstone_cobblestone.getDefaultState(), 0, EnumRitualMatType.DARKSTONE_COBBLESTONE).setTranslationKey("ritualpedestal");
		ACBlocks.ritual_pedestal_abyssal_stone = new BlockRitualPedestal(() -> ACBlocks.abyssal_cobblestone.getDefaultState(), 1, EnumRitualMatType.ABYSSAL_STONE_BRICK).setTranslationKey("ritualpedestal");
		ACBlocks.ritual_pedestal_coralium_stone = new BlockRitualPedestal(() -> ACBlocks.coralium_cobblestone.getDefaultState(), 1, EnumRitualMatType.CORALIUM_STONE_BRICK).setTranslationKey("ritualpedestal");
		ACBlocks.ritual_pedestal_dreadstone = new BlockRitualPedestal(() -> ACBlocks.dreadstone_cobblestone.getDefaultState(), 2, EnumRitualMatType.DREADSTONE_BRICK).setTranslationKey("ritualpedestal");
		ACBlocks.ritual_pedestal_abyssalnite_stone = new BlockRitualPedestal(() -> ACBlocks.abyssalnite_cobblestone.getDefaultState(), 2, EnumRitualMatType.ABYSSALNITE_STONE_BRICK).setTranslationKey("ritualpedestal");
		ACBlocks.ritual_pedestal_ethaxium = new BlockRitualPedestal(() -> ACBlocks.ethaxium_brick.getDefaultState(), 3, EnumRitualMatType.ETHAXIUM_BRICK).setTranslationKey("ritualpedestal");
		ACBlocks.ritual_pedestal_dark_ethaxium = new BlockRitualPedestal(() -> ACBlocks.dark_ethaxium_brick.getDefaultState(), 3, EnumRitualMatType.DARK_ETHAXIUM_BRICK).setTranslationKey("ritualpedestal");
		ACBlocks.shoggoth_ooze = new BlockShoggothOoze().setTranslationKey("shoggothblock");
		ACBlocks.cthulhu_statue = new BlockStatue(EnumDeityType.CTHULHU).setTranslationKey("cthulhustatue");
		ACBlocks.hastur_statue = new BlockStatue(EnumDeityType.HASTUR).setTranslationKey("hasturstatue");
		ACBlocks.jzahar_statue = new BlockStatue(EnumDeityType.JZAHAR).setTranslationKey("jzaharstatue");
		ACBlocks.azathoth_statue = new BlockStatue(EnumDeityType.AZATHOTH).setTranslationKey("azathothstatue");
		ACBlocks.nyarlathotep_statue = new BlockStatue(EnumDeityType.NYARLATHOTEP).setTranslationKey("nyarlathotepstatue");
		ACBlocks.yog_sothoth_statue = new BlockStatue(EnumDeityType.YOGSOTHOTH).setTranslationKey("yogsothothstatue");
		ACBlocks.shub_niggurath_statue = new BlockStatue(EnumDeityType.SHUBNIGGURATH).setTranslationKey("shubniggurathstatue");
		ACBlocks.shoggoth_biomass = new BlockShoggothBiomass();
		ACBlocks.energy_pedestal = new BlockEnergyPedestal();
		ACBlocks.monolith_pillar = new BlockMonolithPillar();
		ACBlocks.sacrificial_altar = new BlockSacrificialAltar();
		ACBlocks.overworld_energy_pedestal = new BlockTieredEnergyPedestal(EnumDimType.OVERWORLD).setTranslationKey("overworld_energy_pedestal");
		ACBlocks.abyssal_wasteland_energy_pedestal = new BlockTieredEnergyPedestal(EnumDimType.ABYSSAL_WASTELAND).setTranslationKey("abyssal_wasteland_energy_pedestal");
		ACBlocks.dreadlands_energy_pedestal = new BlockTieredEnergyPedestal(EnumDimType.DREADLANDS).setTranslationKey("dreadlands_energy_pedestal");
		ACBlocks.omothol_energy_pedestal = new BlockTieredEnergyPedestal(EnumDimType.OMOTHOL).setTranslationKey("omothol_energy_pedestal");
		ACBlocks.overworld_sacrificial_altar = new BlockTieredSacrificialAltar(EnumDimType.OVERWORLD).setTranslationKey("overworld_sacrificial_altar");
		ACBlocks.abyssal_wasteland_sacrificial_altar = new BlockTieredSacrificialAltar(EnumDimType.ABYSSAL_WASTELAND).setTranslationKey("abyssal_wasteland_sacrificial_altar");
		ACBlocks.dreadlands_sacrificial_altar = new BlockTieredSacrificialAltar(EnumDimType.DREADLANDS).setTranslationKey("dreadlands_sacrificial_altar");
		ACBlocks.omothol_sacrificial_altar = new BlockTieredSacrificialAltar(EnumDimType.OMOTHOL).setTranslationKey("omothol_sacrificial_altar");
		ACBlocks.jzahar_spawner = new BlockSingleMobSpawner().setTranslationKey("jzaharspawner");
		ACBlocks.minion_of_the_gatekeeper_spawner = new BlockSingleMobSpawner().setTranslationKey("gatekeeperminionspawner");
		ACBlocks.mimic_fire = new BlockMimicFire().setTranslationKey("fire");
		ACBlocks.decorative_cthulhu_statue = new BlockDecorativeStatue(EnumDeityType.CTHULHU).setTranslationKey("cthulhustatue");
		ACBlocks.decorative_hastur_statue = new BlockDecorativeStatue(EnumDeityType.HASTUR).setTranslationKey("hasturstatue");
		ACBlocks.decorative_jzahar_statue = new BlockDecorativeStatue(EnumDeityType.JZAHAR).setTranslationKey("jzaharstatue");
		ACBlocks.decorative_azathoth_statue = new BlockDecorativeStatue(EnumDeityType.AZATHOTH).setTranslationKey("azathothstatue");
		ACBlocks.decorative_nyarlathotep_statue = new BlockDecorativeStatue(EnumDeityType.NYARLATHOTEP).setTranslationKey("nyarlathotepstatue");
		ACBlocks.decorative_yog_sothoth_statue = new BlockDecorativeStatue(EnumDeityType.YOGSOTHOTH).setTranslationKey("yogsothothstatue");
		ACBlocks.decorative_shub_niggurath_statue = new BlockDecorativeStatue(EnumDeityType.SHUBNIGGURATH).setTranslationKey("shubniggurathstatue");
		ACBlocks.iron_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.IRON);
		ACBlocks.gold_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.GOLD);
		ACBlocks.sulfur_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.SULFUR);
		ACBlocks.carbon_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.CARBON);
		ACBlocks.oxygen_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.OXYGEN);
		ACBlocks.hydrogen_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.HYDROGEN);
		ACBlocks.nitrogen_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.NITROGEN);
		ACBlocks.phosphorus_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.PHOSPHORUS);
		ACBlocks.potassium_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.POTASSIUM);
		ACBlocks.nitrate_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.NITRATE);
		ACBlocks.methane_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.METHANE);
		ACBlocks.redstone_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.REDSTONE);
		ACBlocks.abyssalnite_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.ABYSSALNITE);
		ACBlocks.coralium_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.CORALIUM);
		ACBlocks.dreadium_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.DREADIUM);
		ACBlocks.blaze_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType.BLAZE);
		ACBlocks.tin_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType2.TIN);
		ACBlocks.copper_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType2.COPPER);
		ACBlocks.silicon_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType2.SILICON);
		ACBlocks.magnesium_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType2.MAGNESIUM);
		ACBlocks.aluminium_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType2.ALUMINIUM);
		ACBlocks.silica_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType2.SILICA);
		ACBlocks.alumina_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType2.ALUMINA);
		ACBlocks.magnesia_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType2.MAGNESIA);
		ACBlocks.zinc_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType2.ZINC);
		ACBlocks.calcium_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType2.CALCIUM);
		ACBlocks.beryllium_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType2.BERYLLIUM);
		ACBlocks.beryl_crystal_cluster = new BlockCrystalCluster().remap(EnumCrystalType2.BERYL);
		ACBlocks.energy_collector = new BlockEnergyCollector();
		ACBlocks.energy_relay = new BlockEnergyRelay();
		ACBlocks.energy_container = new BlockEnergyContainer();
		ACBlocks.overworld_energy_collector = new BlockTieredEnergyCollector(EnumDimType.OVERWORLD).setTranslationKey("overworld_energy_collector");
		ACBlocks.abyssal_wasteland_energy_collector = new BlockTieredEnergyCollector(EnumDimType.ABYSSAL_WASTELAND).setTranslationKey("abyssal_wasteland_energy_collector");
		ACBlocks.dreadlands_energy_collector = new BlockTieredEnergyCollector(EnumDimType.DREADLANDS).setTranslationKey("dreadlands_energy_collector");
		ACBlocks.omothol_energy_collector = new BlockTieredEnergyCollector(EnumDimType.OMOTHOL).setTranslationKey("omothol_energy_collector");
		ACBlocks.overworld_energy_relay = new BlockTieredEnergyRelay(EnumDimType.OVERWORLD).setTranslationKey("overworld_energy_relay");
		ACBlocks.abyssal_wasteland_energy_relay = new BlockTieredEnergyRelay(EnumDimType.ABYSSAL_WASTELAND).setTranslationKey("abyssal_wasteland_energy_relay");
		ACBlocks.dreadlands_energy_relay = new BlockTieredEnergyRelay(EnumDimType.DREADLANDS).setTranslationKey("dreadlands_energy_relay");
		ACBlocks.omothol_energy_relay = new BlockTieredEnergyRelay(EnumDimType.OMOTHOL).setTranslationKey("omothol_energy_relay");
		ACBlocks.overworld_energy_container = new BlockTieredEnergyContainer(EnumDimType.OVERWORLD).setTranslationKey("overworld_energy_container");
		ACBlocks.abyssal_wasteland_energy_container = new BlockTieredEnergyContainer(EnumDimType.ABYSSAL_WASTELAND).setTranslationKey("abyssal_wasteland_energy_container");
		ACBlocks.dreadlands_energy_container = new BlockTieredEnergyContainer(EnumDimType.DREADLANDS).setTranslationKey("dreadlands_energy_container");
		ACBlocks.omothol_energy_container = new BlockTieredEnergyContainer(EnumDimType.OMOTHOL).setTranslationKey("omothol_energy_container");
		ACBlocks.abyssal_sand = new BlockAbyssalSand();
		ACBlocks.fused_abyssal_sand = new BlockFusedAbyssalSand();
		ACBlocks.abyssal_sand_glass = new BlockAbyssalSandGlass();
		ACBlocks.dreadlands_dirt = new BlockDreadlandsDirt();
		ACBlocks.abyssal_cobblestone_stairs = new BlockACStairs(ACBlocks.abyssal_cobblestone, "pickaxe", 2).setTranslationKey("abyssalcobblestonestairs");
		ACBlocks.abyssal_cobblestone_slab = new BlockACSingleSlab(Material.ROCK, "pickaxe", 2, SoundType.STONE, MapColor.GREEN).setHardness(2.6F).setResistance(12.0F).setTranslationKey("abyssalcobblestoneslab1");
		abycobbleslab2 = new BlockACDoubleSlab(ACBlocks.abyssal_cobblestone_slab, Material.ROCK, "pickaxe", 2).setHardness(2.6F).setResistance(12.0F).setTranslationKey("abyssalcobblestoneslab2");
		ACBlocks.abyssal_cobblestone_wall = new BlockACWall(ACBlocks.abyssal_cobblestone, 2).setHardness(2.6F).setResistance(12.0F).setTranslationKey("abyssalcobblestonewall");
		ACBlocks.dreadstone_cobblestone_stairs = new BlockACStairs(ACBlocks.dreadstone_cobblestone, "pickaxe", 4).setTranslationKey("dreadstonecobblestonestairs");
		ACBlocks.dreadstone_cobblestone_slab = new BlockACSingleSlab(Material.ROCK, "pickaxe", 4, SoundType.STONE, MapColor.RED).setHardness(3.3F).setResistance(20.0F).setTranslationKey("dreadstonecobblestoneslab1");
		dreadcobbleslab2 = new BlockACDoubleSlab(ACBlocks.dreadstone_cobblestone_slab, Material.ROCK, "pickaxe", 4).setHardness(3.3F).setResistance(20.0F).setTranslationKey("dreadstonecobblestoneslab2");
		ACBlocks.dreadstone_cobblestone_wall = new BlockACWall(ACBlocks.dreadstone_cobblestone, 4).setHardness(3.3F).setResistance(20.0F).setTranslationKey("dreadstonecobblestonewall");
		ACBlocks.abyssalnite_cobblestone_stairs = new BlockACStairs(ACBlocks.abyssalnite_cobblestone, "pickaxe", 4).setTranslationKey("abyssalnitecobblestonestairs");
		ACBlocks.abyssalnite_cobblestone_slab = new BlockACSingleSlab(Material.ROCK, "pickaxe", 4, SoundType.STONE, MapColor.PURPLE).setHardness(3.3F).setResistance(20.0F).setTranslationKey("abyssalnitecobblestoneslab1");
		abydreadcobbleslab2 = new BlockACDoubleSlab(ACBlocks.abyssalnite_cobblestone_slab, Material.ROCK, "pickaxe", 4).setHardness(3.3F).setResistance(20.0F).setTranslationKey("abyssalnitecobblestoneslab2");
		ACBlocks.abyssalnite_cobblestone_wall = new BlockACWall(ACBlocks.abyssalnite_cobblestone, 4).setHardness(3.3F).setResistance(20.0F).setTranslationKey("abyssalnitecobblestonewall");
		ACBlocks.coralium_cobblestone_stairs = new BlockACStairs(ACBlocks.coralium_cobblestone).setTranslationKey("coraliumcobblestonestairs");
		ACBlocks.coralium_cobblestone_slab = new BlockACSingleSlab(Material.ROCK, SoundType.STONE, MapColor.CYAN).setHardness(2.0F).setResistance(10.0F).setTranslationKey("coraliumcobblestoneslab1");
		cstonecobbleslab2 = new BlockACDoubleSlab(ACBlocks.coralium_cobblestone_slab, Material.ROCK).setHardness(2.0F).setResistance(10.0F).setTranslationKey("coraliumcobblestoneslab2");
		ACBlocks.coralium_cobblestone_wall = new BlockACWall(ACBlocks.coralium_cobblestone).setHardness(2.0F).setResistance(10.0F).setTranslationKey("coraliumcobblestonewall");
		ACBlocks.luminous_thistle = new BlockLuminousThistle();
		ACBlocks.wastelands_thorn = new BlockWastelandsThorn();
		ACBlocks.rending_pedestal = new BlockRendingPedestal();
		ACBlocks.state_transformer = new BlockStateTransformer();
		ACBlocks.energy_depositioner = new BlockEnergyDepositioner();
		ACBlocks.calcified_stone = new BlockCalcifiedStone();
		ACBlocks.darklands_oak_door = new BlockACDoor(Material.WOOD, 3.0F, 15.0F, SoundType.WOOD, MapColor.BROWN).setTranslationKey("door_dlt");
		ACBlocks.dreadlands_door = new BlockACDoor(Material.WOOD, 3.0F, 15.0F, SoundType.WOOD, MapColor.RED).setTranslationKey("door_drt");
		ACBlocks.multi_block = new BlockMultiblock();
		ACBlocks.sequential_brewing_stand = new BlockSequentialBrewingStand();
		ACBlocks.portal_anchor = new BlockPortalAnchor();

		GameRegistry.registerTileEntity(TileEntityCrate.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityCrate"));
		GameRegistry.registerTileEntity(TileEntityDGhead.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityDGhead"));
		GameRegistry.registerTileEntity(TileEntityPhead.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityPhead"));
		GameRegistry.registerTileEntity(TileEntityWhead.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityWhead"));
		GameRegistry.registerTileEntity(TileEntityOhead.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityOhead"));
		GameRegistry.registerTileEntity(TileEntityCrystallizer.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityCrystallizer"));
		GameRegistry.registerTileEntity(TileEntityTransmutator.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityTransmutator"));
		GameRegistry.registerTileEntity(TileEntityDreadguardSpawner.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityDradguardSpawner"));
		GameRegistry.registerTileEntity(TileEntityChagarothSpawner.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityChagarothSpawner"));
		GameRegistry.registerTileEntity(TileEntityEngraver.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityEngraver"));
		GameRegistry.registerTileEntity(TileEntityMaterializer.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityMaterializer"));
		GameRegistry.registerTileEntity(TileEntityRitualAltar.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityRitualAltar"));
		GameRegistry.registerTileEntity(TileEntityRitualPedestal.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityRitualPedestal"));
		GameRegistry.registerTileEntity(TileEntityStatue.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityStatue"));
		GameRegistry.registerTileEntity(TileEntityShoggothBiomass.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityShoggothBiomass"));
		GameRegistry.registerTileEntity(TileEntityEnergyPedestal.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityEnergyPedestal"));
		GameRegistry.registerTileEntity(TileEntitySacrificialAltar.class, new ResourceLocation(AbyssalCraft.modid, "tileEntitySacrificialAltar"));
		GameRegistry.registerTileEntity(TileEntityTieredEnergyPedestal.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityTieredEnergyPedestal"));
		GameRegistry.registerTileEntity(TileEntityTieredSacrificialAltar.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityTieredSacrificialAltar"));
		GameRegistry.registerTileEntity(TileEntityJzaharSpawner.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityJzaharSpawner"));
		GameRegistry.registerTileEntity(TileEntityGatekeeperMinionSpawner.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityGatekeeperMinionSpawner"));
		GameRegistry.registerTileEntity(TileEntityEnergyCollector.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityEnergyCollector"));
		GameRegistry.registerTileEntity(TileEntityEnergyRelay.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityEnergyRelay"));
		GameRegistry.registerTileEntity(TileEntityEnergyContainer.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityEnergyContainer"));
		GameRegistry.registerTileEntity(TileEntityTieredEnergyCollector.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityTieredEnergyCollector"));
		GameRegistry.registerTileEntity(TileEntityTieredEnergyRelay.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityTieredEnergyRelay"));
		GameRegistry.registerTileEntity(TileEntityTieredEnergyContainer.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityTieredEnergyContainer"));
		GameRegistry.registerTileEntity(TileEntityRendingPedestal.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityRendingPedestal"));
		GameRegistry.registerTileEntity(TileEntityStateTransformer.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityStateTransformer"));
		GameRegistry.registerTileEntity(TileEntityEnergyDepositioner.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityEnergyDepositioner"));
		GameRegistry.registerTileEntity(TileEntityMultiblock.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityMultiblock"));
		GameRegistry.registerTileEntity(TileEntitySequentialBrewingStand.class, new ResourceLocation(AbyssalCraft.modid, "tileEntitySequentialBrewingStand"));
		GameRegistry.registerTileEntity(TileEntityPortalAnchor.class, new ResourceLocation(AbyssalCraft.modid, "tileEntityPortalAnchor"));

		registerBlock(ACBlocks.darkstone, "darkstone");
		registerBlock(ACBlocks.abyssal_stone, new ItemBlockColorName(ACBlocks.abyssal_stone), "abystone");
		registerBlock(ACBlocks.dreadstone, "dreadstone");
		registerBlock(ACBlocks.abyssalnite_stone, "abydreadstone");
		registerBlock(ACBlocks.coralium_stone, "cstone");
		registerBlock(ACBlocks.ethaxium, new ItemBlockColorName(ACBlocks.ethaxium), "ethaxium");
		registerBlock(ACBlocks.omothol_stone, "omotholstone");
		registerBlock(ACBlocks.monolith_stone, "monolithstone");
		registerBlock(ACBlocks.darkstone_cobblestone, "darkstone_cobble");
		registerBlock(ACBlocks.abyssal_cobblestone, "abyssalcobblestone");
		registerBlock(ACBlocks.dreadstone_cobblestone, "dreadstonecobblestone");
		registerBlock(ACBlocks.abyssalnite_cobblestone, "abyssalnitecobblestone");
		registerBlock(ACBlocks.coralium_cobblestone, "coraliumcobblestone");
		registerBlock(ACBlocks.darkstone_brick, "darkstone_brick");
		registerBlock(ACBlocks.chiseled_darkstone_brick, "chiseled_darkstone_brick");
		registerBlock(ACBlocks.cracked_darkstone_brick, "cracked_darkstone_brick");
		registerBlock(ACBlocks.glowing_darkstone_bricks, "dsglow");
		registerBlock(ACBlocks.darkstone_brick_slab, new ItemSlabAC(ACBlocks.darkstone_brick_slab, ACBlocks.darkstone_brick_slab, Darkbrickslab2), "darkbrickslab1");
		registerBlock(Darkbrickslab2, new ItemSlabAC(Darkbrickslab2, ACBlocks.darkstone_brick_slab, Darkbrickslab2), "darkbrickslab2");
		registerBlock(ACBlocks.darkstone_cobblestone_slab, new ItemSlabAC(ACBlocks.darkstone_cobblestone_slab, ACBlocks.darkstone_cobblestone_slab, Darkcobbleslab2), "darkcobbleslab1");
		registerBlock(Darkcobbleslab2, new ItemSlabAC(Darkcobbleslab2, ACBlocks.darkstone_cobblestone_slab, Darkcobbleslab2), "darkcobbleslab2");
		registerBlock(ACBlocks.darkstone_brick_stairs, "dbstairs");
		registerBlock(ACBlocks.darkstone_cobblestone_stairs, "dcstairs");
		registerBlock(ACBlocks.darklands_oak_leaves, "dltleaves");
		registerBlock(ACBlocks.darklands_oak_wood, "dltlog");
		registerBlock(ACBlocks.darklands_oak_wood_2, "dltlog2");
		registerBlock(ACBlocks.darklands_oak_sapling, "dltsapling");
		registerBlock(ACBlocks.abyssal_stone_brick, new ItemBlockColorName(ACBlocks.abyssal_stone_brick), "abybrick");
		registerBlock(ACBlocks.chiseled_abyssal_stone_brick, new ItemBlockColorName(ACBlocks.chiseled_abyssal_stone_brick), "chiseled_abyssal_stone_brick");
		registerBlock(ACBlocks.cracked_abyssal_stone_brick, new ItemBlockColorName(ACBlocks.cracked_abyssal_stone_brick), "cracked_abyssal_stone_brick");
		registerBlock(ACBlocks.abyssal_stone_brick_slab, new ItemSlabAC(ACBlocks.abyssal_stone_brick_slab, ACBlocks.abyssal_stone_brick_slab, abyslab2).setUnlockCondition(new DimensionCondition(ACLib.abyssal_wasteland_id)), "abyslab1");
		registerBlock(abyslab2, new ItemSlabAC(abyslab2, ACBlocks.abyssal_stone_brick_slab, abyslab2).setUnlockCondition(new DimensionCondition(ACLib.abyssal_wasteland_id)), "abyslab2");
		registerBlock(ACBlocks.abyssal_stone_brick_stairs, new ItemBlockColorName(ACBlocks.abyssal_stone_brick_stairs), "abystairs");
		registerBlock(ACBlocks.coralium_ore, "coraliumore");
		registerBlock(ACBlocks.abyssalnite_ore, "abyore");
		registerBlock(ACBlocks.abyssal_stone_brick_fence, new ItemBlockColorName(ACBlocks.abyssal_stone_brick_fence), "abyfence");
		registerBlock(ACBlocks.darkstone_cobblestone_wall, "dscwall");
		registerBlock(ACBlocks.oblivion_deathbomb, new ItemODB(ACBlocks.oblivion_deathbomb), "odb");
		registerBlock(ACBlocks.block_of_abyssalnite, new ItemBlockColorName(ACBlocks.block_of_abyssalnite), "abyblock");
		registerBlock(ACBlocks.block_of_refined_coralium, new ItemBlockColorName(ACBlocks.block_of_refined_coralium), "corblock");
		registerBlock(ACBlocks.block_of_dreadium, new ItemBlockColorName(ACBlocks.block_of_dreadium), "dreadiumblock");
		registerBlock(ACBlocks.block_of_ethaxium, new ItemBlockColorName(ACBlocks.block_of_ethaxium), "ethaxiumblock");
		registerBlock(ACBlocks.coralium_infused_stone, "coraliumstone");
		registerBlock(ACBlocks.odb_core, new ItemBlockColorName(ACBlocks.odb_core), "odbcore");
		registerBlock(ACBlocks.wooden_crate, "crate");
		registerBlock(ACBlocks.darkstone_slab, new ItemSlabAC(ACBlocks.darkstone_slab, ACBlocks.darkstone_slab, Darkstoneslab2), "darkstoneslab1");
		registerBlock(Darkstoneslab2, new ItemSlabAC(Darkstoneslab2, ACBlocks.darkstone_slab, Darkstoneslab2), "darkstoneslab2");
		registerBlock(ACBlocks.darkstone_button, "dsbutton");
		registerBlock(ACBlocks.darkstone_pressure_plate, "dspplate");
		registerBlock(ACBlocks.darklands_oak_planks, "dltplank");
		registerBlock(ACBlocks.darklands_oak_button, "dltbutton");
		registerBlock(ACBlocks.darklands_oak_pressure_plate, "dltpplate");
		registerBlock(ACBlocks.darklands_oak_stairs, "dltstairs");
		registerBlock(ACBlocks.darklands_oak_slab, new ItemSlabAC(ACBlocks.darklands_oak_slab, ACBlocks.darklands_oak_slab, DLTslab2), "dltslab1");
		registerBlock(DLTslab2, new ItemSlabAC(DLTslab2, ACBlocks.darklands_oak_slab, DLTslab2), "dltslab2");
		registerBlock(ACBlocks.liquid_coralium, "cwater");
		registerBlock(ACBlocks.dreadlands_infused_powerstone, "psdl");
		registerBlock(ACBlocks.abyssal_coralium_ore, "abycorore");
		registerBlock(Altar, "altar");
		registerBlock(ACBlocks.abyssal_stone_button, new ItemBlockColorName(ACBlocks.abyssal_stone_button), "abybutton");
		registerBlock(ACBlocks.abyssal_stone_pressure_plate, new ItemBlockColorName(ACBlocks.abyssal_stone_pressure_plate), "abypplate");
		registerBlock(ACBlocks.darkstone_brick_fence, "dsbfence");
		registerBlock(ACBlocks.darklands_oak_fence, "dltfence");
		registerBlock(ACBlocks.dreadlands_abyssalnite_ore, "abydreadore");
		registerBlock(ACBlocks.dreaded_abyssalnite_ore, "dreadore");
		registerBlock(ACBlocks.dreadstone_brick, "dreadbrick");
		registerBlock(ACBlocks.chiseled_dreadstone_brick, "chiseled_dreadstone_brick");
		registerBlock(ACBlocks.cracked_dreadstone_brick, "cracked_dreadstone_brick");
		registerBlock(ACBlocks.abyssalnite_stone_brick, "abydreadbrick");
		registerBlock(ACBlocks.chiseled_abyssalnite_stone_brick, "chiseled_abyssalnite_stone_brick");
		registerBlock(ACBlocks.cracked_abyssalnite_stone_brick, "cracked_abyssalnite_stone_brick");
		registerBlock(ACBlocks.dreadlands_grass, "dreadgrass");
		registerBlock(ACBlocks.dreadlands_log, "dreadlog");
		registerBlock(ACBlocks.dreadlands_leaves, "dreadleaves");
		registerBlock(ACBlocks.dreadlands_sapling, "dreadsapling");
		registerBlock(ACBlocks.dreadlands_planks, "dreadplanks");
		registerBlock(ACBlocks.depths_ghoul_head, "dghead");
		registerBlock(ACBlocks.pete_head, "phead");
		registerBlock(ACBlocks.mr_wilson_head, "whead");
		registerBlock(ACBlocks.dr_orange_head, "ohead");
		registerBlock(ACBlocks.dreadstone_brick_stairs, "dreadbrickstairs");
		registerBlock(ACBlocks.dreadstone_brick_fence, "dreadbrickfence");
		registerBlock(ACBlocks.dreadstone_brick_slab, new ItemSlabAC(ACBlocks.dreadstone_brick_slab, ACBlocks.dreadstone_brick_slab, dreadbrickslab2).setUnlockCondition(new DimensionCondition(ACLib.dreadlands_id)), "dreadbrickslab1");
		registerBlock(dreadbrickslab2, new ItemSlabAC(dreadbrickslab2, ACBlocks.dreadstone_brick_slab, dreadbrickslab2).setUnlockCondition(new DimensionCondition(ACLib.dreadlands_id)), "dreadbrickslab2");
		registerBlock(ACBlocks.abyssalnite_stone_brick_stairs, "abydreadbrickstairs");
		registerBlock(ACBlocks.abyssalnite_stone_brick_fence, "abydreadbrickfence");
		registerBlock(ACBlocks.abyssalnite_stone_brick_slab, new ItemSlabAC(ACBlocks.abyssalnite_stone_brick_slab, ACBlocks.abyssalnite_stone_brick_slab, abydreadbrickslab2).setUnlockCondition(new DimensionCondition(ACLib.dreadlands_id)), "abydreadbrickslab1");
		registerBlock(abydreadbrickslab2, new ItemSlabAC(abydreadbrickslab2, ACBlocks.abyssalnite_stone_brick_slab, abydreadbrickslab2).setUnlockCondition(new DimensionCondition(ACLib.dreadlands_id)), "abydreadbrickslab2");
		registerBlock(ACBlocks.liquid_antimatter, "antiwater");
		registerBlock(ACBlocks.coralium_stone_brick, "cstonebrick");
		registerBlock(ACBlocks.chiseled_coralium_stone_brick, "chiseled_coralium_stone_brick");
		registerBlock(ACBlocks.cracked_coralium_stone_brick, "cracked_coralium_stone_brick");
		registerBlock(ACBlocks.coralium_stone_brick_fence, "cstonebrickfence");
		registerBlock(ACBlocks.coralium_stone_brick_slab, new ItemSlabAC(ACBlocks.coralium_stone_brick_slab, ACBlocks.coralium_stone_brick_slab, cstonebrickslab2).setUnlockCondition(new DimensionCondition(ACLib.abyssal_wasteland_id)), "cstonebrickslab1");
		registerBlock(cstonebrickslab2, new ItemSlabAC(cstonebrickslab2, ACBlocks.coralium_stone_brick_slab, cstonebrickslab2).setUnlockCondition(new DimensionCondition(ACLib.abyssal_wasteland_id)), "cstonebrickslab2");
		registerBlock(ACBlocks.coralium_stone_brick_stairs, "cstonebrickstairs");
		registerBlock(ACBlocks.coralium_stone_button, "cstonebutton");
		registerBlock(ACBlocks.coralium_stone_pressure_plate, "cstonepplate");
		registerBlock(ACBlocks.chagaroth_altar_top, "dreadaltartop");
		registerBlock(ACBlocks.chagaroth_altar_bottom, "dreadaltarbottom");
		registerBlock(ACBlocks.crystallizer_idle, "crystallizer");
		registerBlock(ACBlocks.crystallizer_active, "crystallizer_on");
		registerBlock(ACBlocks.transmutator_idle, "transmutator");
		registerBlock(ACBlocks.transmutator_active, "transmutator_on");
		registerBlock(ACBlocks.dreadguard_spawner, "dreadguardspawner");
		registerBlock(ACBlocks.chagaroth_spawner, "chagarothspawner");
		registerBlock(ACBlocks.dreadlands_wood_fence, "drtfence");
		registerBlock(ACBlocks.nitre_ore, "nitreore");
		registerBlock(ACBlocks.abyssal_iron_ore, "abyiroore");
		registerBlock(ACBlocks.abyssal_gold_ore, "abygolore");
		registerBlock(ACBlocks.abyssal_diamond_ore, "abydiaore");
		registerBlock(ACBlocks.abyssal_nitre_ore, "abynitore");
		registerBlock(ACBlocks.abyssal_tin_ore, "abytinore");
		registerBlock(ACBlocks.abyssal_copper_ore, "abycopore");
		registerBlock(ACBlocks.pearlescent_coralium_ore, "abypcorore");
		registerBlock(ACBlocks.liquified_coralium_ore, "abylcorore");
		registerBlock(ACBlocks.solid_lava, "solidlava");
		registerBlock(ACBlocks.ethaxium_brick, new ItemBlockColorName(ACBlocks.ethaxium_brick), "ethaxiumbrick");
		registerBlock(ACBlocks.chiseled_ethaxium_brick, new ItemBlockColorName(ACBlocks.chiseled_ethaxium_brick), "chiseled_ethaxium_brick");
		registerBlock(ACBlocks.cracked_ethaxium_brick, new ItemBlockColorName(ACBlocks.cracked_ethaxium_brick), "cracked_ethaxium_brick");
		registerBlock(ACBlocks.ethaxium_pillar, new ItemBlockColorName(ACBlocks.ethaxium_pillar), "ethaxiumpillar");
		registerBlock(ACBlocks.ethaxium_brick_stairs, new ItemBlockColorName(ACBlocks.ethaxium_brick_stairs), "ethaxiumbrickstairs");
		registerBlock(ACBlocks.ethaxium_brick_slab, new ItemSlabAC(ACBlocks.ethaxium_brick_slab, ACBlocks.ethaxium_brick_slab, ethaxiumslab2).setUnlockCondition(new DimensionCondition(ACLib.omothol_id)), "ethaxiumbrickslab1");
		registerBlock(ethaxiumslab2, new ItemSlabAC(ethaxiumslab2, ACBlocks.ethaxium_brick_slab, ethaxiumslab2).setUnlockCondition(new DimensionCondition(ACLib.omothol_id)), "ethaxiumbrickslab2");
		registerBlock(ACBlocks.ethaxium_brick_fence, new ItemBlockColorName(ACBlocks.ethaxium_brick_fence), "ethaxiumfence");
		registerBlock(ACBlocks.engraver, "engraver");
		registerBlock(house, "engraver_on");
		registerBlock(ACBlocks.materializer, "materializer");
		registerBlock(ACBlocks.dark_ethaxium_brick, new ItemBlockColorName(ACBlocks.dark_ethaxium_brick), "darkethaxiumbrick");
		registerBlock(ACBlocks.chiseled_dark_ethaxium_brick, new ItemBlockColorName(ACBlocks.chiseled_dark_ethaxium_brick), "chiseled_dark_ethaxium_brick");
		registerBlock(ACBlocks.cracked_dark_ethaxium_brick, new ItemBlockColorName(ACBlocks.cracked_dark_ethaxium_brick), "cracked_dark_ethaxium_brick");
		registerBlock(ACBlocks.dark_ethaxium_pillar, new ItemBlockColorName(ACBlocks.dark_ethaxium_pillar), "darkethaxiumpillar");
		registerBlock(ACBlocks.dark_ethaxium_brick_stairs, new ItemBlockColorName(ACBlocks.dark_ethaxium_brick_stairs), "darkethaxiumbrickstairs");
		registerBlock(ACBlocks.dark_ethaxium_brick_slab, new ItemSlabAC(ACBlocks.dark_ethaxium_brick_slab, ACBlocks.dark_ethaxium_brick_slab, darkethaxiumslab2).setUnlockCondition(new DimensionCondition(ACLib.omothol_id)), "darkethaxiumbrickslab1");
		registerBlock(darkethaxiumslab2, new ItemSlabAC(darkethaxiumslab2, ACBlocks.dark_ethaxium_brick_slab, darkethaxiumslab2).setUnlockCondition(new DimensionCondition(ACLib.omothol_id)), "darkethaxiumbrickslab2");
		registerBlock(ACBlocks.dark_ethaxium_brick_fence, new ItemBlockColorName(ACBlocks.dark_ethaxium_brick_fence), "darkethaxiumbrickfence");
		registerBlock(ACBlocks.ritual_altar_stone, "ritual_altar_stone");
		registerBlock(ACBlocks.ritual_altar_darkstone, "ritual_altar_darkstone");
		registerBlock(ACBlocks.ritual_altar_abyssal_stone, "ritual_altar_abyssal_stone");
		registerBlock(ACBlocks.ritual_altar_coralium_stone, "ritual_altar_coralium_stone");
		registerBlock(ACBlocks.ritual_altar_dreadstone, "ritual_altar_dreadstone");
		registerBlock(ACBlocks.ritual_altar_abyssalnite_stone, "ritual_altar_abyssalnite_stone");
		registerBlock(ACBlocks.ritual_altar_ethaxium, "ritual_altar_ethaxium");
		registerBlock(ACBlocks.ritual_altar_dark_ethaxium, "ritual_altar_dark_ethaxium");
		registerBlock(ACBlocks.ritual_pedestal_stone, "ritual_pedestal_stone");
		registerBlock(ACBlocks.ritual_pedestal_darkstone, "ritual_pedestal_darkstone");
		registerBlock(ACBlocks.ritual_pedestal_abyssal_stone, "ritual_pedestal_abyssal_stone");
		registerBlock(ACBlocks.ritual_pedestal_coralium_stone, "ritual_pedestal_coralium_stone");
		registerBlock(ACBlocks.ritual_pedestal_dreadstone, "ritual_pedestal_dreadstone");
		registerBlock(ACBlocks.ritual_pedestal_abyssalnite_stone, "ritual_pedestal_abyssalnite_stone");
		registerBlock(ACBlocks.ritual_pedestal_ethaxium, "ritual_pedestal_ethaxium");
		registerBlock(ACBlocks.ritual_pedestal_dark_ethaxium, "ritual_pedestal_dark_ethaxium");
		registerBlock(ACBlocks.shoggoth_ooze, new ItemShoggothOoze(ACBlocks.shoggoth_ooze), "shoggothblock");
		registerBlock(ACBlocks.cthulhu_statue, "cthulhustatue");
		registerBlock(ACBlocks.hastur_statue, "hasturstatue");
		registerBlock(ACBlocks.jzahar_statue, "jzaharstatue");
		registerBlock(ACBlocks.azathoth_statue, "azathothstatue");
		registerBlock(ACBlocks.nyarlathotep_statue, "nyarlathotepstatue");
		registerBlock(ACBlocks.yog_sothoth_statue, "yogsothothstatue");
		registerBlock(ACBlocks.shub_niggurath_statue, "shubniggurathstatue");
		registerBlock(ACBlocks.shoggoth_biomass, "shoggothbiomass");
		registerBlock(ACBlocks.energy_pedestal, new ItemPEContainerBlock(ACBlocks.energy_pedestal), "energypedestal");
		registerBlock(ACBlocks.monolith_pillar, "monolithpillar");
		registerBlock(ACBlocks.sacrificial_altar, new ItemPEContainerBlock(ACBlocks.sacrificial_altar), "sacrificialaltar");
		registerBlock(ACBlocks.overworld_energy_pedestal, new ItemPEContainerBlock(ACBlocks.overworld_energy_pedestal), "overworld_energy_pedestal");
		registerBlock(ACBlocks.abyssal_wasteland_energy_pedestal, new ItemPEContainerBlock(ACBlocks.abyssal_wasteland_energy_pedestal), "abyssal_wasteland_energy_pedestal");
		registerBlock(ACBlocks.dreadlands_energy_pedestal, new ItemPEContainerBlock(ACBlocks.dreadlands_energy_pedestal), "dreadlands_energy_pedestal");
		registerBlock(ACBlocks.omothol_energy_pedestal, new ItemPEContainerBlock(ACBlocks.omothol_energy_pedestal), "omothol_energy_pedestal");
		registerBlock(ACBlocks.overworld_sacrificial_altar, new ItemPEContainerBlock(ACBlocks.overworld_sacrificial_altar), "overworld_sacrificial_altar");
		registerBlock(ACBlocks.abyssal_wasteland_sacrificial_altar, new ItemPEContainerBlock(ACBlocks.abyssal_wasteland_sacrificial_altar), "abyssal_wasteland_sacrificial_altar");
		registerBlock(ACBlocks.dreadlands_sacrificial_altar, new ItemPEContainerBlock(ACBlocks.dreadlands_sacrificial_altar), "dreadlands_sacrificial_altar");
		registerBlock(ACBlocks.omothol_sacrificial_altar, new ItemPEContainerBlock(ACBlocks.omothol_sacrificial_altar), "omothol_sacrificial_altar");
		registerBlock(ACBlocks.jzahar_spawner, "jzaharspawner");
		registerBlock(ACBlocks.minion_of_the_gatekeeper_spawner, "gatekeeperminionspawner");
		registerBlock(ACBlocks.mimic_fire, "fire");
		registerBlock(ACBlocks.decorative_cthulhu_statue, new ItemDecorativeStatueBlock(ACBlocks.decorative_cthulhu_statue), "decorativecthulhustatue");
		registerBlock(ACBlocks.decorative_hastur_statue, new ItemDecorativeStatueBlock(ACBlocks.decorative_hastur_statue), "decorativehasturstatue");
		registerBlock(ACBlocks.decorative_jzahar_statue, new ItemDecorativeStatueBlock(ACBlocks.decorative_jzahar_statue), "decorativejzaharstatue");
		registerBlock(ACBlocks.decorative_azathoth_statue, new ItemDecorativeStatueBlock(ACBlocks.decorative_azathoth_statue), "decorativeazathothstatue");
		registerBlock(ACBlocks.decorative_nyarlathotep_statue, new ItemDecorativeStatueBlock(ACBlocks.decorative_nyarlathotep_statue), "decorativenyarlathotepstatue");
		registerBlock(ACBlocks.decorative_yog_sothoth_statue, new ItemDecorativeStatueBlock(ACBlocks.decorative_yog_sothoth_statue), "decorativeyogsothothstatue");
		registerBlock(ACBlocks.decorative_shub_niggurath_statue, new ItemDecorativeStatueBlock(ACBlocks.decorative_shub_niggurath_statue), "decorativeshubniggurathstatue");
		registerBlock(ACBlocks.iron_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.iron_crystal_cluster), "iron_crystal_cluster");
		registerBlock(ACBlocks.gold_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.gold_crystal_cluster), "gold_crystal_cluster");
		registerBlock(ACBlocks.sulfur_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.sulfur_crystal_cluster), "sulfur_crystal_cluster");
		registerBlock(ACBlocks.carbon_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.carbon_crystal_cluster), "carbon_crystal_cluster");
		registerBlock(ACBlocks.oxygen_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.oxygen_crystal_cluster), "oxygen_crystal_cluster");
		registerBlock(ACBlocks.hydrogen_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.hydrogen_crystal_cluster), "hydrogen_crystal_cluster");
		registerBlock(ACBlocks.nitrogen_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.nitrogen_crystal_cluster), "nitrogen_crystal_cluster");
		registerBlock(ACBlocks.phosphorus_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.phosphorus_crystal_cluster), "phosphorus_crystal_cluster");
		registerBlock(ACBlocks.potassium_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.potassium_crystal_cluster), "potassium_crystal_cluster");
		registerBlock(ACBlocks.nitrate_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.nitrate_crystal_cluster), "nitrate_crystal_cluster");
		registerBlock(ACBlocks.methane_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.methane_crystal_cluster), "methane_crystal_cluster");
		registerBlock(ACBlocks.redstone_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.redstone_crystal_cluster), "redstone_crystal_cluster");
		registerBlock(ACBlocks.abyssalnite_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.abyssalnite_crystal_cluster), "abyssalnite_crystal_cluster");
		registerBlock(ACBlocks.coralium_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.coralium_crystal_cluster), "coralium_crystal_cluster");
		registerBlock(ACBlocks.dreadium_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.dreadium_crystal_cluster), "dreadium_crystal_cluster");
		registerBlock(ACBlocks.blaze_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.blaze_crystal_cluster), "blaze_crystal_cluster");
		registerBlock(ACBlocks.tin_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.tin_crystal_cluster), "tin_crystal_cluster");
		registerBlock(ACBlocks.copper_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.copper_crystal_cluster), "copper_crystal_cluster");
		registerBlock(ACBlocks.silicon_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.silicon_crystal_cluster), "silicon_crystal_cluster");
		registerBlock(ACBlocks.magnesium_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.magnesium_crystal_cluster), "magnesium_crystal_cluster");
		registerBlock(ACBlocks.aluminium_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.aluminium_crystal_cluster), "aluminium_crystal_cluster");
		registerBlock(ACBlocks.silica_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.silica_crystal_cluster), "silica_crystal_cluster");
		registerBlock(ACBlocks.alumina_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.alumina_crystal_cluster), "alumina_crystal_cluster");
		registerBlock(ACBlocks.magnesia_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.magnesia_crystal_cluster), "magnesia_crystal_cluster");
		registerBlock(ACBlocks.zinc_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.zinc_crystal_cluster), "zinc_crystal_cluster");
		registerBlock(ACBlocks.calcium_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.calcium_crystal_cluster), "calcium_crystal_cluster");
		registerBlock(ACBlocks.beryllium_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.beryllium_crystal_cluster), "beryllium_crystal_cluster");
		registerBlock(ACBlocks.beryl_crystal_cluster, new ItemCrystalClusterBlock(ACBlocks.beryl_crystal_cluster), "beryl_crystal_cluster");
		registerBlock(ACBlocks.energy_collector, new ItemPEContainerBlock(ACBlocks.energy_collector), "energycollector");
		registerBlock(ACBlocks.energy_relay, new ItemPEContainerBlock(ACBlocks.energy_relay), "energyrelay");
		registerBlock(ACBlocks.energy_container, new ItemPEContainerBlock(ACBlocks.energy_container), "energycontainer");
		registerBlock(ACBlocks.overworld_energy_collector, new ItemPEContainerBlock(ACBlocks.overworld_energy_collector), "overworld_energy_collector");
		registerBlock(ACBlocks.abyssal_wasteland_energy_collector, new ItemPEContainerBlock(ACBlocks.abyssal_wasteland_energy_collector), "abyssal_wasteland_energy_collector");
		registerBlock(ACBlocks.dreadlands_energy_collector, new ItemPEContainerBlock(ACBlocks.dreadlands_energy_collector), "dreadlands_energy_collector");
		registerBlock(ACBlocks.omothol_energy_collector, new ItemPEContainerBlock(ACBlocks.omothol_energy_collector), "omothol_energy_collector");
		registerBlock(ACBlocks.overworld_energy_relay, new ItemPEContainerBlock(ACBlocks.overworld_energy_relay), "overworld_energy_relay");
		registerBlock(ACBlocks.abyssal_wasteland_energy_relay, new ItemPEContainerBlock(ACBlocks.abyssal_wasteland_energy_relay), "abyssal_wasteland_energy_relay");
		registerBlock(ACBlocks.dreadlands_energy_relay, new ItemPEContainerBlock(ACBlocks.dreadlands_energy_relay), "dreadlands_energy_relay");
		registerBlock(ACBlocks.omothol_energy_relay, new ItemPEContainerBlock(ACBlocks.omothol_energy_relay), "omothol_energy_relay");
		registerBlock(ACBlocks.overworld_energy_container, new ItemPEContainerBlock(ACBlocks.overworld_energy_container), "overworld_energy_container");
		registerBlock(ACBlocks.abyssal_wasteland_energy_container, new ItemPEContainerBlock(ACBlocks.abyssal_wasteland_energy_container), "abyssal_wasteland_energy_container");
		registerBlock(ACBlocks.dreadlands_energy_container, new ItemPEContainerBlock(ACBlocks.dreadlands_energy_container), "dreadlands_energy_container");
		registerBlock(ACBlocks.omothol_energy_container, new ItemPEContainerBlock(ACBlocks.omothol_energy_container), "omothol_energy_container");
		registerBlock(ACBlocks.abyssal_sand, "abyssalsand");
		registerBlock(ACBlocks.fused_abyssal_sand, "fusedabyssalsand");
		registerBlock(ACBlocks.abyssal_sand_glass, "abyssalsandglass");
		registerBlock(ACBlocks.dreadlands_dirt, "dreadlandsdirt");
		registerBlock(ACBlocks.abyssal_cobblestone_stairs, "abyssalcobblestonestairs");
		registerBlock(ACBlocks.abyssal_cobblestone_slab, new ItemSlabAC(ACBlocks.abyssal_cobblestone_slab, ACBlocks.abyssal_cobblestone_slab, abycobbleslab2).setUnlockCondition(new DimensionCondition(ACLib.abyssal_wasteland_id)), "abyssalcobblestoneslab1");
		registerBlock(abycobbleslab2, new ItemSlabAC(abycobbleslab2, ACBlocks.abyssal_cobblestone_slab, abycobbleslab2).setUnlockCondition(new DimensionCondition(ACLib.abyssal_wasteland_id)), "abyssalcobblestoneslab2");
		registerBlock(ACBlocks.abyssal_cobblestone_wall, "abyssalcobblestonewall");
		registerBlock(ACBlocks.dreadstone_cobblestone_stairs, "dreadstonecobblestonestairs");
		registerBlock(ACBlocks.dreadstone_cobblestone_slab, new ItemSlabAC(ACBlocks.dreadstone_cobblestone_slab, ACBlocks.dreadstone_cobblestone_slab, dreadcobbleslab2).setUnlockCondition(new DimensionCondition(ACLib.dreadlands_id)), "dreadstonecobblestoneslab1");
		registerBlock(dreadcobbleslab2, new ItemSlabAC(dreadcobbleslab2, ACBlocks.dreadstone_cobblestone_slab, dreadcobbleslab2).setUnlockCondition(new DimensionCondition(ACLib.dreadlands_id)), "dreadstonecobblestoneslab2");
		registerBlock(ACBlocks.dreadstone_cobblestone_wall, "dreadstonecobblestonewall");
		registerBlock(ACBlocks.abyssalnite_cobblestone_stairs, "abyssalnitecobblestonestairs");
		registerBlock(ACBlocks.abyssalnite_cobblestone_slab, new ItemSlabAC(ACBlocks.abyssalnite_cobblestone_slab, ACBlocks.abyssalnite_cobblestone_slab, abydreadcobbleslab2).setUnlockCondition(new DimensionCondition(ACLib.dreadlands_id)), "abyssalnitecobblestoneslab1");
		registerBlock(abydreadcobbleslab2, new ItemSlabAC(abydreadcobbleslab2, ACBlocks.abyssalnite_cobblestone_slab, abydreadcobbleslab2).setUnlockCondition(new DimensionCondition(ACLib.dreadlands_id)), "abyssalnitecobblestoneslab2");
		registerBlock(ACBlocks.abyssalnite_cobblestone_wall, "abyssalnitecobblestonewall");
		registerBlock(ACBlocks.coralium_cobblestone_stairs, "coraliumcobblestonestairs");
		registerBlock(ACBlocks.coralium_cobblestone_slab, new ItemSlabAC(ACBlocks.coralium_cobblestone_slab, ACBlocks.coralium_cobblestone_slab, cstonecobbleslab2).setUnlockCondition(new DimensionCondition(ACLib.abyssal_wasteland_id)), "coraliumcobblestoneslab1");
		registerBlock(cstonecobbleslab2, new ItemSlabAC(cstonecobbleslab2, ACBlocks.coralium_cobblestone_slab, cstonecobbleslab2).setUnlockCondition(new DimensionCondition(ACLib.abyssal_wasteland_id)), "coraliumcobblestoneslab2");
		registerBlock(ACBlocks.coralium_cobblestone_wall, "coraliumcobblestonewall");
		registerBlock(ACBlocks.luminous_thistle, "luminousthistle");
		registerBlock(ACBlocks.wastelands_thorn, "wastelandsthorn");
		registerBlock(ACBlocks.rending_pedestal, new ItemRendingPedestalBlock(ACBlocks.rending_pedestal), "rendingpedestal");
		registerBlock(ACBlocks.state_transformer, "statetransformer");
		registerBlock(ACBlocks.energy_depositioner, "energydepositioner");
		registerBlock(ACBlocks.calcified_stone, "calcifiedstone");
		registerBlock(ACBlocks.darklands_oak_door, null, "door_dlt");
		registerBlock(ACBlocks.dreadlands_door, null, "door_drt");
		registerBlock(ACBlocks.multi_block, "multiblock");
		registerBlock(ACBlocks.sequential_brewing_stand, "sequential_brewing_stand");
		registerBlock(ACBlocks.portal_anchor, "portal_anchor");

		Blocks.FIRE.setFireInfo(ACBlocks.darklands_oak_planks, 5, 20);
		Blocks.FIRE.setFireInfo(DLTslab2, 5, 20);
		Blocks.FIRE.setFireInfo(ACBlocks.darklands_oak_slab, 5, 20);
		Blocks.FIRE.setFireInfo(ACBlocks.darklands_oak_fence, 5, 20);
		Blocks.FIRE.setFireInfo(ACBlocks.darklands_oak_stairs, 5, 20);
		Blocks.FIRE.setFireInfo(ACBlocks.darklands_oak_wood, 5, 5);
		Blocks.FIRE.setFireInfo(ACBlocks.darklands_oak_wood_2, 5, 5);
		Blocks.FIRE.setFireInfo(ACBlocks.darklands_oak_leaves, 30, 60);

		Blocks.FIRE.setFireInfo(ACBlocks.dreadlands_planks, 5, 20);
		Blocks.FIRE.setFireInfo(ACBlocks.dreadlands_wood_fence, 5, 20);
		Blocks.FIRE.setFireInfo(ACBlocks.dreadlands_log, 5, 5);
		Blocks.FIRE.setFireInfo(ACBlocks.dreadlands_leaves, 30, 60);
	}

	@Override
	public void init(FMLInitializationEvent event) {

		addCondition(ACBlocks.abyssal_stone_brick, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.chiseled_abyssal_stone_brick, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.cracked_abyssal_stone_brick, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.abyssal_stone_brick_stairs, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.abyssalnite_ore, new BiomePredicateCondition(b -> b instanceof IDarklandsBiome));
		addCondition(ACBlocks.abyssal_stone_brick_fence, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.oblivion_deathbomb, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.dreadlands_infused_powerstone, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.abyssal_coralium_ore, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.abyssal_stone_button, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.abyssal_stone_pressure_plate, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.dreaded_abyssalnite_ore, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.dreadlands_abyssalnite_ore, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.dreadstone_brick, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.chiseled_dreadstone_brick, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.cracked_dreadstone_brick, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.abyssalnite_stone_brick, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.chiseled_abyssalnite_stone_brick, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.cracked_abyssalnite_stone_brick, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.dreadlands_sapling, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.dreadlands_log, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.dreadlands_leaves, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.dreadlands_planks, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.depths_ghoul_head, new EntityCondition("abyssalcraft:depthsghoul"));
		addCondition(ACBlocks.dreadlands_grass, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.pete_head, new EntityCondition("abyssalcraft:depthsghoul"));
		addCondition(ACBlocks.mr_wilson_head, new EntityCondition("abyssalcraft:depthsghoul"));
		addCondition(ACBlocks.dr_orange_head, new EntityCondition("abyssalcraft:depthsghoul"));
		addCondition(ACBlocks.dreadstone_brick_stairs, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.dreadstone_brick_fence, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.abyssalnite_stone_brick_stairs, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.abyssalnite_stone_brick_fence, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.coralium_stone_brick, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.chiseled_coralium_stone_brick, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.cracked_coralium_stone_brick, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.coralium_stone_brick_fence, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.coralium_stone_brick_stairs, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.coralium_stone_button, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.coralium_stone_pressure_plate, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.chagaroth_altar_top, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.chagaroth_altar_bottom, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.crystallizer_idle, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.crystallizer_active, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.transmutator_idle, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.transmutator_active, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.dreadlands_wood_fence, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.abyssal_iron_ore, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.abyssal_gold_ore, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.abyssal_diamond_ore, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.pearlescent_coralium_ore, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.liquified_coralium_ore, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.ethaxium_brick, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.chiseled_ethaxium_brick, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.cracked_ethaxium_brick, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.ethaxium_pillar, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.ethaxium_brick_stairs, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.ethaxium_brick_fence, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.engraver, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.materializer, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.dark_ethaxium_brick, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.chiseled_dark_ethaxium_brick, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.cracked_dark_ethaxium_brick, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.dark_ethaxium_pillar, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.dark_ethaxium_brick_stairs, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.dark_ethaxium_brick_fence, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.abyssal_sand, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.fused_abyssal_sand, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.abyssal_sand_glass, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.dreadlands_dirt, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.abyssal_cobblestone_stairs, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.abyssal_cobblestone_wall, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.dreadstone_cobblestone_stairs, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.dreadstone_cobblestone_wall, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.abyssalnite_cobblestone_stairs, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.abyssalnite_cobblestone_wall, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.coralium_cobblestone_stairs, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.coralium_cobblestone_wall, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.luminous_thistle, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.wastelands_thorn, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.sequential_brewing_stand, new DimensionCondition(-1));
		addCondition(ACBlocks.abyssal_stone, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.abyssal_cobblestone, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.coralium_stone, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.coralium_cobblestone, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.dreadstone, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.abyssalnite_stone, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.dreadstone_cobblestone, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.abyssalnite_cobblestone, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.ethaxium, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.omothol_stone, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.block_of_abyssalnite, new BiomePredicateCondition(b -> b instanceof IDarklandsBiome));
		addCondition(ACBlocks.block_of_refined_coralium, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.block_of_dreadium, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.block_of_ethaxium, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.abyssal_wasteland_energy_pedestal, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.dreadlands_energy_pedestal, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.omothol_energy_pedestal, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.abyssal_wasteland_sacrificial_altar, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.dreadlands_sacrificial_altar, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.omothol_sacrificial_altar, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.abyssal_wasteland_energy_collector, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.dreadlands_energy_collector, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.omothol_energy_collector, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.abyssal_wasteland_energy_relay, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.dreadlands_energy_relay, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.omothol_energy_relay, new DimensionCondition(ACLib.omothol_id));
		addCondition(ACBlocks.abyssal_wasteland_energy_container, new DimensionCondition(ACLib.abyssal_wasteland_id));
		addCondition(ACBlocks.dreadlands_energy_container, new DimensionCondition(ACLib.dreadlands_id));
		addCondition(ACBlocks.omothol_energy_container, new DimensionCondition(ACLib.omothol_id));
	}

	private void addCondition(Block block, IUnlockCondition condition){
		((IUnlockableItem) Item.getItemFromBlock(block)).setUnlockCondition(condition);
	}

	@Override
	public void postInit(FMLPostInitializationEvent event) {
		((BlockCLiquid) ACBlocks.liquid_coralium).addBlocks();
	}

	@Override
	public void loadComplete(FMLLoadCompleteEvent event) {}

	private static void registerItem(Item item, String name){
		if(item != null)
			InitHandler.INSTANCE.ITEMS.add(item.setRegistryName(new ResourceLocation(AbyssalCraft.modid, name)));
	}

	private static void registerBlock(Block block, String name){
		registerBlock(block, new ItemBlockAC(block), name);
	}

	private static void registerBlock(Block block, ItemBlock item, String name){
		InitHandler.INSTANCE.BLOCKS.add(block.setRegistryName(new ResourceLocation(AbyssalCraft.modid, name)));
		registerItem(item, name);
	}
}
