/*******************************************************************************
 * AbyssalCraft
 * Copyright (c) 2012 - 2016 Shinoow.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser Public License v3
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-3.0.txt
 * 
 * Contributors:
 *     Shinoow -  implementation
 ******************************************************************************/
package com.shinoow.abyssalcraft.init;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.item.ItemStack;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.world.World;
import net.minecraftforge.fml.common.event.*;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.oredict.OreDictionary;

import com.shinoow.abyssalcraft.AbyssalCraft;
import com.shinoow.abyssalcraft.api.AbyssalCraftAPI;
import com.shinoow.abyssalcraft.api.block.ACBlocks;
import com.shinoow.abyssalcraft.common.blocks.*;
import com.shinoow.abyssalcraft.common.blocks.itemblock.*;
import com.shinoow.abyssalcraft.common.blocks.tile.*;
import com.shinoow.abyssalcraft.common.world.gen.WorldGenDLT;
import com.shinoow.abyssalcraft.common.world.gen.WorldGenDrT;
import com.shinoow.abyssalcraft.lib.ACTabs;

public class BlockHandler implements ILifeCycleHandler {

	@Override
	public void preInit(FMLPreInitializationEvent event) {
		ACBlocks.darkstone = new BlockDarkstone().setCreativeTab(ACTabs.tabBlock).setStepSound(Block.soundTypeStone).setHardness(1.65F).setResistance(12.0F).setUnlocalizedName("darkstone");
		ACBlocks.darkstone_brick = new BlockACBrick(1.65F, 12.0F).setUnlocalizedName("darkstone_brick");
		ACBlocks.darkstone_cobblestone = new BlockACBasic(Material.rock, 2.2F, 12.0F, Block.soundTypeStone).setUnlocalizedName("darkstone_cobble");
		ACBlocks.glowing_darkstone_bricks = new BlockACBasic(Material.rock, "pickaxe", 3, 55F, 3000F, Block.soundTypeStone).setCreativeTab(ACTabs.tabBlock).setLightLevel(1.0F).setUnlocalizedName("dsglow");
		ACBlocks.darkstone_brick_slab = new BlockACSingleSlab(Material.rock).setStepSound(Block.soundTypeStone).setHardness(1.65F).setResistance(12.0F).setUnlocalizedName("darkbrickslab1");
		AbyssalCraft.Darkbrickslab2 = new BlockACDoubleSlab(ACBlocks.darkstone_brick_slab, Material.rock).setStepSound(Block.soundTypeStone).setHardness(1.65F).setResistance(12.0F).setUnlocalizedName("darkbrickslab2");
		ACBlocks.darkstone_cobblestone_slab = new BlockACSingleSlab(Material.rock).setStepSound(Block.soundTypeStone).setHardness(1.65F) .setResistance(12.0F).setUnlocalizedName("darkcobbleslab1");
		AbyssalCraft.Darkcobbleslab2 = new BlockACDoubleSlab(ACBlocks.darkstone_cobblestone_slab, Material.rock).setStepSound(Block.soundTypeStone).setHardness(1.65F) .setResistance(12.0F).setUnlocalizedName("darkcobbleslab2");
		ACBlocks.darklands_grass = new BlockDarklandsgrass().setStepSound(Block.soundTypeGrass).setCreativeTab(ACTabs.tabBlock).setHardness(0.4F).setUnlocalizedName("darkgrass");
		ACBlocks.darkstone_brick_stairs = new BlockACStairs(ACBlocks.darkstone_brick).setStepSound(Block.soundTypeStone).setHardness(1.65F).setResistance(12.0F).setUnlocalizedName("dbstairs");
		ACBlocks.darkstone_cobblestone_stairs = new BlockACStairs(ACBlocks.darkstone_cobblestone).setStepSound(Block.soundTypeStone).setHardness(1.65F).setResistance(12.0F).setUnlocalizedName("dcstairs");
		ACBlocks.darklands_oak_sapling = new BlockACSapling(new WorldGenDLT(true)).setStepSound(Block.soundTypeGrass).setHardness(0.0F).setResistance(0.0F).setUnlocalizedName("dltsapling");
		ACBlocks.darklands_oak_leaves = new BlockACLeaves(ACBlocks.darklands_oak_sapling).setStepSound(Block.soundTypeGrass).setHardness(0.2F).setResistance(1.0F).setUnlocalizedName("dltleaves");
		ACBlocks.darklands_oak_wood = new BlockACLog().setStepSound(Block.soundTypeWood).setHardness(2.0F).setResistance(1.0F).setUnlocalizedName("dltlog");
		ACBlocks.abyssal_stone = new BlockACBasic(Material.rock, "pickaxe", 2, 1.8F, 12.0F, Block.soundTypeStone).setUnlocalizedName("abystone");
		ACBlocks.abyssal_stone_brick = new BlockACBrick(2, 1.8F, 12.0F).setUnlocalizedName("abybrick");
		ACBlocks.abyssal_stone_brick_slab = new BlockACSingleSlab(Material.rock, "pickaxe", 2).setCreativeTab(ACTabs.tabBlock).setStepSound(Block.soundTypeStone).setHardness(1.8F).setResistance(12.0F).setUnlocalizedName("abyslab1");
		AbyssalCraft.abyslab2 = new BlockACDoubleSlab(ACBlocks.abyssal_stone_brick_slab, Material.rock, "pickaxe", 2).setStepSound(Block.soundTypeStone).setHardness(1.8F).setResistance(12.0F).setUnlocalizedName("abyslab2");
		ACBlocks.abyssal_stone_brick_stairs = new BlockACStairs(ACBlocks.abyssal_stone_brick, "pickaxe", 2).setStepSound(Block.soundTypeStone).setHardness(1.65F).setResistance(12.0F).setUnlocalizedName("abystairs");
		ACBlocks.coralium_ore = new BlockACOre(2, 3.0F, 6.0F).setUnlocalizedName("coraliumore");
		ACBlocks.abyssalnite_ore = new BlockACOre(2, 3.0F, 6.0F).setUnlocalizedName("abyore");
		ACBlocks.abyssal_stone_brick_fence = new BlockACFence(Material.rock, "pickaxe", 2).setHardness(1.8F).setResistance(12.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("abyfence");
		ACBlocks.darkstone_cobblestone_wall = new BlockDarkstonecobblewall(ACBlocks.darkstone_cobblestone).setHardness(1.65F).setResistance(12.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("dscwall");
		ACBlocks.wooden_crate = new BlockCrate().setStepSound(Block.soundTypeStone).setHardness(3.0F).setResistance(6.0F).setUnlocalizedName("crate");
		ACBlocks.oblivion_deathbomb = new BlockODB().setStepSound(Block.soundTypeMetal).setHardness(3.0F).setResistance(0F).setUnlocalizedName("odb");
		ACBlocks.block_of_abyssalnite = new IngotBlock(2).setUnlocalizedName("abyblock");
		ACBlocks.coralium_infused_stone = new BlockACOre(3, 3.0F, 6.0F).setUnlocalizedName("coraliumstone");
		ACBlocks.odb_core = new BlockODBcore().setStepSound(Block.soundTypeMetal).setHardness(3.0F).setResistance(0F).setUnlocalizedName("odbcore");
		ACBlocks.abyssal_gateway = new BlockAbyssPortal().setUnlocalizedName("abyportal");
		ACBlocks.darkstone_slab = new BlockACSingleSlab(Material.rock).setStepSound(Block.soundTypeStone).setCreativeTab(ACTabs.tabBlock).setHardness(1.65F).setResistance(12.0F).setUnlocalizedName("darkstoneslab1");
		AbyssalCraft.Darkstoneslab2 = new BlockACDoubleSlab(ACBlocks.darkstone_slab, Material.rock).setStepSound(Block.soundTypeStone).setHardness(1.65F).setResistance(12.0F).setUnlocalizedName("darkstoneslab2");
		ACBlocks.coralium_fire = new BlockCoraliumfire().setLightLevel(1.0F).setUnlocalizedName("coraliumfire");
		ACBlocks.darkstone_button = new BlockACButton(true, "DS").setHardness(0.6F).setResistance(12.0F).setUnlocalizedName("dsbutton");
		ACBlocks.darkstone_pressure_plate = new BlockACPressureplate("DS", Material.rock, BlockACPressureplate.Sensitivity.MOBS).setHardness(0.6F).setResistance(12.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("dspplate");
		ACBlocks.darklands_oak_planks = new BlockACBasic(Material.wood, 2.0F, 5.0F, Block.soundTypeWood).setUnlocalizedName("dltplank");
		ACBlocks.darklands_oak_button = new BlockACButton(true, "DLTplank").setHardness(0.5F).setUnlocalizedName("dltbutton");
		ACBlocks.darklands_oak_pressure_plate = new BlockACPressureplate("DLTplank", Material.wood, BlockACPressureplate.Sensitivity.EVERYTHING).setHardness(0.5F).setStepSound(Block.soundTypeWood).setUnlocalizedName("dltpplate");
		ACBlocks.darklands_oak_stairs = new BlockACStairs(ACBlocks.darklands_oak_planks).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundTypeWood).setUnlocalizedName("dltstairs");
		ACBlocks.darklands_oak_slab = new BlockACSingleSlab(Material.wood).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundTypeWood).setUnlocalizedName("dltslab1");
		AbyssalCraft.DLTslab2 = new BlockACDoubleSlab(ACBlocks.darklands_oak_slab, Material.wood).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundTypeWood).setUnlocalizedName("dltslab2");
		ACBlocks.block_of_coralium = new IngotBlock(5).setUnlocalizedName("corblock");
		ACBlocks.dreadlands_infused_powerstone = new BlockPSDL().setHardness(50.0F).setResistance(3000F).setCreativeTab(ACTabs.tabDecoration).setUnlocalizedName("psdl");
		ACBlocks.abyssal_coralium_ore = new BlockACOre(3, 3.0F, 6.0F).setUnlocalizedName("abycorore");
		AbyssalCraft.Altar = new BlockAltar().setStepSound(Block.soundTypeStone).setHardness(4.0F).setResistance(300.0F).setUnlocalizedName("altar");
		ACBlocks.abyssal_stone_button = new BlockACButton(false, "pickaxe", 2, "AS").setHardness(0.8F).setResistance(12.0F).setUnlocalizedName("abybutton");
		ACBlocks.abyssal_stone_pressure_plate = new BlockACPressureplate("AS", Material.rock, BlockACPressureplate.Sensitivity.MOBS, "pickaxe", 2).setHardness(0.8F).setResistance(12.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("abypplate");
		ACBlocks.darkstone_brick_fence = new BlockACFence(Material.rock).setHardness(1.65F).setResistance(12.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("dsbfence");
		ACBlocks.darklands_oak_fence = new BlockACFence(Material.wood).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundTypeWood).setUnlocalizedName("dltfence");
		ACBlocks.dreaded_abyssalnite_ore = new BlockACOre(4, 2.5F, 20.0F).setUnlocalizedName("dreadore");
		ACBlocks.dreadlands_abyssalnite_ore = new BlockACOre(4, 2.5F, 20.0F).setUnlocalizedName("abydreadore");
		ACBlocks.dreadstone_brick = new BlockACBrick(4, 2.5F, 20.0F).setUnlocalizedName("dreadbrick");
		ACBlocks.abyssalnite_stone_brick = new BlockACBrick(4, 2.5F, 20.0F).setUnlocalizedName("abydreadbrick");
		ACBlocks.dreadlands_sapling = new BlockACSapling(new WorldGenDrT(true)).setStepSound(Block.soundTypeGrass).setHardness(0.0F).setResistance(0.0F).setUnlocalizedName("dreadsapling");
		ACBlocks.dreadlands_log = new BlockACLog().setHardness(2.0F).setResistance(12.0F).setStepSound(Block.soundTypeWood).setUnlocalizedName("dreadlog");
		ACBlocks.dreadlands_leaves = new BlockACLeaves(ACBlocks.dreadlands_sapling).setStepSound(Block.soundTypeGrass).setHardness(0.2F).setResistance(1.0F).setUnlocalizedName("dreadleaves");
		ACBlocks.dreadlands_planks = new BlockACBasic(Material.wood, 2.0F, 5.0F, Block.soundTypeWood).setUnlocalizedName("dreadplanks");
		ACBlocks.dreaded_gateway = new BlockDreadlandsPortal().setUnlocalizedName("dreadportal");
		ACBlocks.dreaded_fire = new BlockDreadFire().setLightLevel(1.0F).setUnlocalizedName("dreadfire");
		ACBlocks.depths_ghoul_head = new BlockDGhead(){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityDGhead(); }}.setUnlocalizedName("dghead");
		ACBlocks.liquid_coralium = new BlockCLiquid().setResistance(500.0F).setLightLevel(1.0F).setUnlocalizedName("cwater");
		ACBlocks.dreadstone = new BlockACBasic(Material.rock, "pickaxe", 4, 2.5F, 20.0F, Block.soundTypeStone).setUnlocalizedName("dreadstone");
		ACBlocks.abyssalnite_stone = new BlockACBasic(Material.rock, "pickaxe", 4, 2.5F, 20.0F, Block.soundTypeStone).setUnlocalizedName("abydreadstone");
		ACBlocks.dreadlands_grass = new BlockDreadGrass().setHardness(0.4F).setStepSound(Block.soundTypeGrass).setUnlocalizedName("dreadgrass");
		ACBlocks.pete_head = new BlockDGhead(){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityPhead(); }}.setUnlocalizedName("phead");
		ACBlocks.mr_wilson_head = new BlockDGhead(){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityWhead(); }}.setUnlocalizedName("whead");
		ACBlocks.dr_orange_head = new BlockDGhead(){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityOhead(); }}.setUnlocalizedName("ohead");
		ACBlocks.dreadstone_brick_stairs = new BlockACStairs(ACBlocks.dreadstone_brick, "pickaxe", 4).setHardness(2.5F).setResistance(20.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("dreadbrickstairs");
		ACBlocks.dreadstone_brick_fence = new BlockACFence(Material.rock, "pickaxe", 4).setHardness(2.5F).setResistance(20.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("dreadbrickfence");
		ACBlocks.dreadstone_brick_slab = new BlockACSingleSlab(Material.rock, "pickaxe", 4).setHardness(2.5F).setResistance(20.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("dreadbrickslab1");
		AbyssalCraft.dreadbrickslab2 = new BlockACDoubleSlab(ACBlocks.dreadstone_brick_slab, Material.rock, "pickaxe", 4).setHardness(2.5F).setResistance(20.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("dreadbrickslab2");
		ACBlocks.abyssalnite_stone_brick_stairs = new BlockACStairs(ACBlocks.abyssalnite_stone_brick, "pickaxe", 4).setHardness(2.5F).setResistance(20.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("abydreadbrickstairs");
		ACBlocks.abyssalnite_stone_brick_fence = new BlockACFence(Material.rock, "pickaxe", 4).setHardness(2.5F).setResistance(20.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("abydreadbrickfence");
		ACBlocks.abyssalnite_stone_brick_slab = new BlockACSingleSlab(Material.rock, "pickaxe", 4).setHardness(2.5F).setResistance(20.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("abydreadbrickslab1");
		AbyssalCraft.abydreadbrickslab2 = new BlockACDoubleSlab(ACBlocks.abyssalnite_stone_brick_slab, Material.rock, "pickaxe", 4).setHardness(2.5F).setResistance(20.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("abydreadbrickslab2");
		ACBlocks.liquid_antimatter = new BlockAntiliquid().setResistance(500.0F).setLightLevel(0.5F).setUnlocalizedName("antiwater");
		ACBlocks.coralium_stone = new BlockCoraliumstone().setHardness(1.5F).setResistance(10.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("cstone");
		ACBlocks.coralium_stone_brick = new BlockACBrick(1.5F, 10.0F).setUnlocalizedName("cstonebrick");
		ACBlocks.coralium_stone_brick_fence = new BlockACFence(Material.rock).setHardness(1.5F).setResistance(10.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("cstonebrickfence");
		ACBlocks.coralium_stone_brick_slab = new BlockACSingleSlab(Material.rock).setHardness(1.5F).setResistance(10.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("cstonebrickslab1");
		AbyssalCraft.cstonebrickslab2 = new BlockACDoubleSlab(ACBlocks.coralium_stone_brick_slab, Material.rock).setHardness(1.5F).setResistance(10.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("cstonebrickslab2");
		ACBlocks.coralium_stone_brick_stairs = new BlockACStairs(ACBlocks.coralium_stone_brick, "pickaxe", 0).setHardness(1.5F).setResistance(10.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("cstonebrickstairs");
		ACBlocks.coralium_stone_button = new BlockACButton(false, "cstone").setHardness(0.6F).setResistance(12.0F).setUnlocalizedName("cstonebutton");
		ACBlocks.coralium_stone_pressure_plate = new BlockACPressureplate("cstone", Material.rock, BlockACPressureplate.Sensitivity.MOBS).setHardness(0.6F).setResistance(12.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("cstonepplate");
		ACBlocks.chagaroth_altar_top = new BlockDreadAltarTop().setHardness(30.0F).setResistance(300.0F).setStepSound(Block.soundTypeStone).setCreativeTab(ACTabs.tabDecoration).setUnlocalizedName("dreadaltartop");
		ACBlocks.chagaroth_altar_bottom = new BlockDreadAltarBottom().setHardness(30.0F).setResistance(300.0F).setStepSound(Block.soundTypeStone).setCreativeTab(ACTabs.tabDecoration).setUnlocalizedName("dreadaltarbottom");
		ACBlocks.crystallizer_idle = new BlockCrystallizer(false).setHardness(2.5F).setResistance(12.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("crystallizer");
		ACBlocks.crystallizer_active = new BlockCrystallizer(true).setHardness(2.5F).setResistance(12.0F).setStepSound(Block.soundTypeStone).setLightLevel(0.875F).setUnlocalizedName("crystallizer_on");
		ACBlocks.block_of_dreadium = new IngotBlock(6).setUnlocalizedName("dreadiumblock");
		ACBlocks.transmutator_idle = new BlockTransmutator(false).setHardness(2.5F).setResistance(12.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("transmutator");
		ACBlocks.transmutator_active = new BlockTransmutator(true).setHardness(2.5F).setResistance(12.0F).setStepSound(Block.soundTypeStone).setLightLevel(0.875F).setUnlocalizedName("transmutator_on");
		ACBlocks.dreadguard_spawner = new BlockDreadguardSpawner().setUnlocalizedName("dreadguardspawner");
		ACBlocks.chagaroth_spawner = new BlockChagarothSpawner().setUnlocalizedName("chagarothspawner");
		ACBlocks.dreadlands_wood_fence = new BlockACFence(Material.wood).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundTypeWood).setUnlocalizedName("drtfence");
		ACBlocks.nitre_ore = new BlockACOre(2, 3.0F, 6.0F).setUnlocalizedName("nitreore");
		ACBlocks.abyssal_iron_ore = new BlockACOre(2, 3.0F, 6.0F).setUnlocalizedName("abyiroore");
		ACBlocks.abyssal_gold_ore = new BlockACOre(2, 5.0F, 10.0F).setUnlocalizedName("abygolore");
		ACBlocks.abyssal_diamond_ore = new BlockACOre(2, 5.0F, 10.0F).setUnlocalizedName("abydiaore");
		ACBlocks.abyssal_nitre_ore = new BlockACOre(2, 3.0F, 6.0F).setUnlocalizedName("abynitore");
		ACBlocks.abyssal_tin_ore = new BlockACOre(2, 3.0F, 6.0F).setUnlocalizedName("abytinore");
		ACBlocks.abyssal_copper_ore = new BlockACOre(2, 3.0F, 6.0F).setUnlocalizedName("abycopore");
		ACBlocks.pearlescent_coralium_ore = new BlockACOre(5, 8.0F, 10.0F).setUnlocalizedName("abypcorore");
		ACBlocks.liquified_coralium_ore = new BlockACOre(4, 10.0F, 12.0F).setUnlocalizedName("abylcorore");
		ACBlocks.solid_lava = new BlockSolidLava("solidlava");
		ACBlocks.ethaxium = new BlockACBasic(Material.rock, "pickaxe", 8, 100.0F, Float.MAX_VALUE, Block.soundTypeStone).setUnlocalizedName("ethaxium");
		ACBlocks.ethaxium_brick = new BlockACBrick(8, 100.0F, Float.MAX_VALUE).setUnlocalizedName("ethaxiumbrick");
		ACBlocks.ethaxium_pillar = new BlockEthaxiumPillar(100.0F).setUnlocalizedName("ethaxiumpillar");
		ACBlocks.ethaxium_brick_stairs = new BlockACStairs(ACBlocks.ethaxium_brick, "pickaxe", 8).setHardness(100.0F).setResistance(Float.MAX_VALUE).setStepSound(Block.soundTypeStone).setUnlocalizedName("ethaxiumbrickstairs");
		ACBlocks.ethaxium_brick_slab = new BlockACSingleSlab(Material.rock, "pickaxe", 8).setHardness(100.0F).setResistance(Float.MAX_VALUE).setStepSound(Block.soundTypeStone).setUnlocalizedName("ethaxiumbrickslab1");
		AbyssalCraft.ethaxiumslab2 = new BlockACDoubleSlab(ACBlocks.ethaxium_brick_slab, Material.rock, "pickaxe", 8).setHardness(100.0F).setResistance(Float.MAX_VALUE).setStepSound(Block.soundTypeStone).setUnlocalizedName("ethaxiumbrickslab2");
		ACBlocks.ethaxium_brick_fence = new BlockACFence(Material.rock, "pickaxe", 8).setHardness(100.0F).setResistance(Float.MAX_VALUE).setStepSound(Block.soundTypeStone).setUnlocalizedName("ethaxiumfence");
		ACBlocks.omothol_stone = new BlockACBasic(Material.rock, "pickaxe", 6, 10.0F, 12.0F, Block.soundTypeStone).setUnlocalizedName("omotholstone");
		ACBlocks.block_of_ethaxium = new IngotBlock(8).setResistance(Float.MAX_VALUE).setUnlocalizedName("ethaxiumblock");
		ACBlocks.omothol_gateway = new BlockOmotholPortal().setUnlocalizedName("omotholportal");
		ACBlocks.omothol_fire = new BlockOmotholFire().setLightLevel(1.0F).setUnlocalizedName("omotholfire");
		ACBlocks.engraver = new BlockEngraver().setHardness(2.5F).setResistance(12.0F).setStepSound(Block.soundTypeStone).setUnlocalizedName("engraver");
		AbyssalCraft.house = new BlockHouse().setHardness(1.0F).setResistance(Float.MAX_VALUE).setStepSound(Block.soundTypeWood).setUnlocalizedName("engraver_on");
		ACBlocks.materializer = new BlockMaterializer().setUnlocalizedName("materializer");
		ACBlocks.dark_ethaxium_brick = new BlockACBrick(8, 150.0F, Float.MAX_VALUE).setUnlocalizedName("darkethaxiumbrick");
		ACBlocks.dark_ethaxium_pillar = new BlockEthaxiumPillar(150.0F).setUnlocalizedName("darkethaxiumpillar");
		ACBlocks.dark_ethaxium_brick_stairs = new BlockACStairs(ACBlocks.dark_ethaxium_brick, "pickaxe", 8).setHardness(150.0F).setResistance(Float.MAX_VALUE).setStepSound(Block.soundTypeStone).setUnlocalizedName("darkethaxiumbrickstairs");
		ACBlocks.dark_ethaxium_brick_slab = new BlockACSingleSlab(Material.rock, "pickaxe", 8).setHardness(150.0F).setResistance(Float.MAX_VALUE).setStepSound(Block.soundTypeStone).setUnlocalizedName("darkethaxiumbrickslab1");
		AbyssalCraft.darkethaxiumslab2 = new BlockACDoubleSlab(ACBlocks.dark_ethaxium_brick_slab, Material.rock, "pickaxe", 8).setHardness(150.0F).setResistance(Float.MAX_VALUE).setStepSound(Block.soundTypeStone).setUnlocalizedName("darkethaxiumbrickslab2");
		ACBlocks.dark_ethaxium_brick_fence = new BlockACFence(Material.rock, "pickaxe", 8).setHardness(150.0F).setResistance(Float.MAX_VALUE).setStepSound(Block.soundTypeStone).setUnlocalizedName("darkethaxiumbrickfence");
		ACBlocks.ritual_altar = new BlockRitualAltar().setUnlocalizedName("ritualaltar");
		ACBlocks.ritual_pedestal = new BlockRitualPedestal().setUnlocalizedName("ritualpedestal");
		ACBlocks.shoggoth_ooze = new BlockShoggothOoze().setUnlocalizedName("shoggothblock");
		ACBlocks.cthulhu_statue = new BlockStatue(){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityCthulhuStatue(); }}.setUnlocalizedName("cthulhustatue");
		ACBlocks.hastur_statue = new BlockStatue(){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityHasturStatue(); }}.setUnlocalizedName("hasturstatue");
		ACBlocks.jzahar_statue = new BlockStatue(){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityJzaharStatue(); }}.setUnlocalizedName("jzaharstatue");
		ACBlocks.azathoth_statue = new BlockStatue(){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityAzathothStatue(); }}.setUnlocalizedName("azathothstatue");
		ACBlocks.nyarlathotep_statue = new BlockStatue(){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityNyarlathotepStatue(); }}.setUnlocalizedName("nyarlathotepstatue");
		ACBlocks.yog_sothoth_statue = new BlockStatue(){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityYogsothothStatue(); }}.setUnlocalizedName("yogsothothstatue");
		ACBlocks.shub_niggurath_statue = new BlockStatue(){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityShubniggurathStatue(); }}.setUnlocalizedName("shubniggurathstatue");
		ACBlocks.monolith_stone = new BlockACBasic(Material.rock, 6.0F, 24.0F, Block.soundTypeStone).setUnlocalizedName("monolithstone");
		ACBlocks.shoggoth_biomass = new BlockShoggothBiomass();
		ACBlocks.energy_pedestal = new BlockEnergyPedestal();
		ACBlocks.monolith_pillar = new BlockMonolithPillar();
		ACBlocks.sacrificial_altar = new BlockSacrificialAltar();
		ACBlocks.tiered_energy_pedestal = new BlockTieredEnergyPedestal();
		ACBlocks.tiered_sacrificial_altar = new BlockTieredSacrificialAltar();
		ACBlocks.jzahar_spawner = new BlockJzaharSpawner().setUnlocalizedName("jzaharspawner");
		ACBlocks.minion_of_the_gatekeeper_spawner = new BlockGatekeeperMinionSpawner().setUnlocalizedName("gatekeeperminionspawner");
		ACBlocks.mimic_fire = new BlockMimicFire().setUnlocalizedName("fire");
		ACBlocks.decorative_cthulhu_statue = new BlockDecorativeStatue().setUnlocalizedName("cthulhustatue");
		ACBlocks.decorative_hastur_statue = new BlockDecorativeStatue().setUnlocalizedName("hasturstatue");
		ACBlocks.decorative_jzahar_statue = new BlockDecorativeStatue().setUnlocalizedName("jzaharstatue");
		ACBlocks.decorative_azathoth_statue = new BlockDecorativeStatue().setUnlocalizedName("azathothstatue");
		ACBlocks.decorative_nyarlathotep_statue = new BlockDecorativeStatue().setUnlocalizedName("nyarlathotepstatue");
		ACBlocks.decorative_yog_sothoth_statue = new BlockDecorativeStatue().setUnlocalizedName("yogsothothstatue");
		ACBlocks.decorative_shub_niggurath_statue = new BlockDecorativeStatue().setUnlocalizedName("shubniggurathstatue");
		ACBlocks.crystal_cluster = new BlockCrystalCluster().setUnlocalizedName("crystalcluster");
		ACBlocks.energy_collector = new BlockEnergyCollector();
		ACBlocks.energy_relay = new BlockEnergyRelay();
		ACBlocks.energy_container = new BlockEnergyContainer();
		ACBlocks.tiered_energy_collector = new BlockTieredEnergyCollector();
		ACBlocks.overworld_energy_relay = new BlockTieredEnergyRelay("owenergyrelay"){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityOverworldEnergyRelay(); }};
		ACBlocks.abyssal_wasteland_energy_relay = new BlockTieredEnergyRelay("awenergyrelay"){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityAbyssalWastelandEnergyRelay(); }};
		ACBlocks.dreadlands_energy_relay = new BlockTieredEnergyRelay("dlenergyrelay"){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityDreadlandsEnergyRelay(); }};
		ACBlocks.omothol_energy_relay = new BlockTieredEnergyRelay("omtenergyrelay"){ @Override public TileEntity createNewTileEntity(World worldIn, int meta) { return new TileEntityOmotholEnergyRelay(); }};
		ACBlocks.tiered_energy_container = new BlockTieredEnergyContainer();

		((BlockShoggothOoze) ACBlocks.shoggoth_ooze).initBlacklist();

		GameRegistry.registerTileEntity(TileEntityCrate.class, "tileEntityCrate");
		GameRegistry.registerTileEntity(TileEntityDGhead.class, "tileEntityDGhead");
		GameRegistry.registerTileEntity(TileEntityPhead.class, "tileEntityPhead");
		GameRegistry.registerTileEntity(TileEntityWhead.class, "tileEntityWhead");
		GameRegistry.registerTileEntity(TileEntityOhead.class, "tileEntityOhead");
		GameRegistry.registerTileEntity(TileEntityCrystallizer.class, "tileEntityCrystallizer");
		GameRegistry.registerTileEntity(TileEntityTransmutator.class, "tileEntityTransmutator");
		GameRegistry.registerTileEntity(TileEntityDreadguardSpawner.class, "tileEntityDradguardSpawner");
		GameRegistry.registerTileEntity(TileEntityChagarothSpawner.class, "tileEntityChagarothSpawner");
		GameRegistry.registerTileEntity(TileEntityEngraver.class, "tileEntityEngraver");
		GameRegistry.registerTileEntity(TileEntityMaterializer.class, "tileEntityMaterializer");
		GameRegistry.registerTileEntity(TileEntityRitualAltar.class, "tileEntityRitualAltar");
		GameRegistry.registerTileEntity(TileEntityRitualPedestal.class, "tileEntityRitualPedestal");
		GameRegistry.registerTileEntity(TileEntityCthulhuStatue.class, "tileEntityCthulhuStatue");
		GameRegistry.registerTileEntity(TileEntityHasturStatue.class, "tileEntityHasturStatue");
		GameRegistry.registerTileEntity(TileEntityJzaharStatue.class, "tileEntityJzaharStatue");
		GameRegistry.registerTileEntity(TileEntityAzathothStatue.class, "tileEntityAzathothStatue");
		GameRegistry.registerTileEntity(TileEntityNyarlathotepStatue.class, "tileEntityNyarlathotepStatue");
		GameRegistry.registerTileEntity(TileEntityYogsothothStatue.class, "tileEntityyogsothothStatue");
		GameRegistry.registerTileEntity(TileEntityShubniggurathStatue.class, "tileEntityShubniggurathStatue");
		GameRegistry.registerTileEntity(TileEntityShoggothBiomass.class, "tileEntityShoggothBiomass");
		GameRegistry.registerTileEntity(TileEntityEnergyPedestal.class, "tileEntityEnergyPedestal");
		GameRegistry.registerTileEntity(TileEntitySacrificialAltar.class, "tileEntitySacrificialAltar");
		GameRegistry.registerTileEntity(TileEntityTieredEnergyPedestal.class, "tileEntityTieredEnergyPedestal");
		GameRegistry.registerTileEntity(TileEntityTieredSacrificialAltar.class, "tileEntityTieredSacrificialAltar");
		GameRegistry.registerTileEntity(TileEntityJzaharSpawner.class, "tileEntityJzaharSpawner");
		GameRegistry.registerTileEntity(TileEntityGatekeeperMinionSpawner.class, "tileEntityGatekeeperMinionSpawner");
		GameRegistry.registerTileEntity(TileEntityEnergyCollector.class, "tileEntityEnergyCollector");
		GameRegistry.registerTileEntity(TileEntityEnergyRelay.class, "tileEntityEnergyRelay");
		GameRegistry.registerTileEntity(TileEntityEnergyContainer.class, "tileEntityEnergyContainer");
		GameRegistry.registerTileEntity(TileEntityTieredEnergyCollector.class, "tileEntityTieredEnergyCollector");
		GameRegistry.registerTileEntity(TileEntityOverworldEnergyRelay.class, "tileEntityOverworldEnergyRelay");
		GameRegistry.registerTileEntity(TileEntityAbyssalWastelandEnergyRelay.class, "tileEntityAbyssalWastelandEnergyRelay");
		GameRegistry.registerTileEntity(TileEntityDreadlandsEnergyRelay.class, "tileEntityDreadlandsEnergyRelay");
		GameRegistry.registerTileEntity(TileEntityOmotholEnergyRelay.class, "tileEntityOmotholEnergyRelay");
		GameRegistry.registerTileEntity(TileEntityTieredEnergyContainer.class, "tileEntityTieredEnergyContainer");

		GameRegistry.registerBlock(ACBlocks.darkstone, "darkstone");
		GameRegistry.registerBlock(ACBlocks.darkstone_cobblestone, "darkstone_cobble");
		GameRegistry.registerBlock(ACBlocks.darkstone_brick, ItemMetadataBlock.class, "darkstone_brick");
		GameRegistry.registerBlock(ACBlocks.glowing_darkstone_bricks, "dsglow");
		GameRegistry.registerBlock(ACBlocks.darkstone_brick_slab, ItemDarkbrickSlab.class, "darkbrickslab1");
		GameRegistry.registerBlock(AbyssalCraft.Darkbrickslab2, ItemDarkbrickSlab.class, "darkbrickslab2");
		GameRegistry.registerBlock(ACBlocks.darkstone_cobblestone_slab, ItemDarkcobbleSlab.class, "darkcobbleslab1");
		GameRegistry.registerBlock(AbyssalCraft.Darkcobbleslab2, ItemDarkcobbleSlab.class, "darkcobbleslab2");
		GameRegistry.registerBlock(ACBlocks.darklands_grass, "darkgrass");
		GameRegistry.registerBlock(ACBlocks.darkstone_brick_stairs, "dbstairs");
		GameRegistry.registerBlock(ACBlocks.darkstone_cobblestone_stairs, "dcstairs");
		GameRegistry.registerBlock(ACBlocks.darklands_oak_leaves, "dltleaves");
		GameRegistry.registerBlock(ACBlocks.darklands_oak_wood, "dltlog");
		GameRegistry.registerBlock(ACBlocks.darklands_oak_sapling, "dltsapling");
		GameRegistry.registerBlock(ACBlocks.abyssal_stone, ItemBlockColorName.class, "abystone");
		GameRegistry.registerBlock(ACBlocks.abyssal_stone_brick, ItemMetadataBlock.class, "abybrick");
		GameRegistry.registerBlock(ACBlocks.abyssal_stone_brick_slab, ItemAbySlab.class, "abyslab1");
		GameRegistry.registerBlock(AbyssalCraft.abyslab2, ItemAbySlab.class, "abyslab2");
		GameRegistry.registerBlock(ACBlocks.abyssal_stone_brick_stairs, ItemBlockColorName.class, "abystairs");
		GameRegistry.registerBlock(ACBlocks.coralium_ore, "coraliumore");
		GameRegistry.registerBlock(ACBlocks.abyssalnite_ore, "abyore");
		GameRegistry.registerBlock(ACBlocks.abyssal_stone_brick_fence, ItemBlockColorName.class, "abyfence");
		GameRegistry.registerBlock(ACBlocks.darkstone_cobblestone_wall, "dscwall");
		GameRegistry.registerBlock(ACBlocks.oblivion_deathbomb, ItemODB.class, "odb");
		GameRegistry.registerBlock(ACBlocks.block_of_abyssalnite, ItemBlockColorName.class, "abyblock");
		GameRegistry.registerBlock(ACBlocks.coralium_infused_stone, "coraliumstone");
		GameRegistry.registerBlock(ACBlocks.odb_core, ItemBlockColorName.class, "odbcore");
		GameRegistry.registerBlock(ACBlocks.wooden_crate, "crate");
		GameRegistry.registerBlock(ACBlocks.abyssal_gateway, "abyportal");
		GameRegistry.registerBlock(ACBlocks.darkstone_slab, ItemDarkstoneSlab.class, "darkstoneslab1");
		GameRegistry.registerBlock(AbyssalCraft.Darkstoneslab2, ItemDarkstoneSlab.class, "darkstoneslab2");
		GameRegistry.registerBlock(ACBlocks.coralium_fire, "coraliumfire");
		GameRegistry.registerBlock(ACBlocks.darkstone_button, "dsbutton");
		GameRegistry.registerBlock(ACBlocks.darkstone_pressure_plate, "dspplate");
		GameRegistry.registerBlock(ACBlocks.darklands_oak_planks, "dltplank");
		GameRegistry.registerBlock(ACBlocks.darklands_oak_button, "dltbutton");
		GameRegistry.registerBlock(ACBlocks.darklands_oak_pressure_plate, "dltpplate");
		GameRegistry.registerBlock(ACBlocks.darklands_oak_stairs, "dltstairs");
		GameRegistry.registerBlock(ACBlocks.darklands_oak_slab, ItemDLTSlab.class, "dltslab1");
		GameRegistry.registerBlock(AbyssalCraft.DLTslab2, ItemDLTSlab.class, "dltslab2");
		GameRegistry.registerBlock(ACBlocks.liquid_coralium, "cwater");
		GameRegistry.registerBlock(ACBlocks.block_of_coralium, ItemBlockColorName.class, "corblock");
		GameRegistry.registerBlock(ACBlocks.dreadlands_infused_powerstone, "psdl");
		GameRegistry.registerBlock(ACBlocks.abyssal_coralium_ore, "abycorore");
		GameRegistry.registerBlock(AbyssalCraft.Altar, "altar");
		GameRegistry.registerBlock(ACBlocks.abyssal_stone_button, ItemBlockColorName.class, "abybutton");
		GameRegistry.registerBlock(ACBlocks.abyssal_stone_pressure_plate, ItemBlockColorName.class, "abypplate");
		GameRegistry.registerBlock(ACBlocks.darkstone_brick_fence, "dsbfence");
		GameRegistry.registerBlock(ACBlocks.darklands_oak_fence, "dltfence");
		GameRegistry.registerBlock(ACBlocks.dreadstone, "dreadstone");
		GameRegistry.registerBlock(ACBlocks.abyssalnite_stone, "abydreadstone");
		GameRegistry.registerBlock(ACBlocks.dreadlands_abyssalnite_ore, "abydreadore");
		GameRegistry.registerBlock(ACBlocks.dreaded_abyssalnite_ore, "dreadore");
		GameRegistry.registerBlock(ACBlocks.dreadstone_brick, ItemMetadataBlock.class, "dreadbrick");
		GameRegistry.registerBlock(ACBlocks.abyssalnite_stone_brick, ItemMetadataBlock.class, "abydreadbrick");
		GameRegistry.registerBlock(ACBlocks.dreadlands_grass, "dreadgrass");
		GameRegistry.registerBlock(ACBlocks.dreadlands_log, "dreadlog");
		GameRegistry.registerBlock(ACBlocks.dreadlands_leaves, "dreadleaves");
		GameRegistry.registerBlock(ACBlocks.dreadlands_sapling, "dreadsapling");
		GameRegistry.registerBlock(ACBlocks.dreadlands_planks, "dreadplanks");
		GameRegistry.registerBlock(ACBlocks.dreaded_gateway, "dreadportal");
		GameRegistry.registerBlock(ACBlocks.dreaded_fire, "dreadfire");
		GameRegistry.registerBlock(ACBlocks.depths_ghoul_head, "dghead");
		GameRegistry.registerBlock(ACBlocks.pete_head, "phead");
		GameRegistry.registerBlock(ACBlocks.mr_wilson_head, "whead");
		GameRegistry.registerBlock(ACBlocks.dr_orange_head, "ohead");
		GameRegistry.registerBlock(ACBlocks.dreadstone_brick_stairs, "dreadbrickstairs");
		GameRegistry.registerBlock(ACBlocks.dreadstone_brick_fence, "dreadbrickfence");
		GameRegistry.registerBlock(ACBlocks.dreadstone_brick_slab, ItemDreadbrickSlab.class, "dreadbrickslab1");
		GameRegistry.registerBlock(AbyssalCraft.dreadbrickslab2, ItemDreadbrickSlab.class, "dreadbrickslab2");
		GameRegistry.registerBlock(ACBlocks.abyssalnite_stone_brick_stairs, "abydreadbrickstairs");
		GameRegistry.registerBlock(ACBlocks.abyssalnite_stone_brick_fence, "abydreadbrickfence");
		GameRegistry.registerBlock(ACBlocks.abyssalnite_stone_brick_slab, ItemAbyDreadbrickSlab.class, "abydreadbrickslab1");
		GameRegistry.registerBlock(AbyssalCraft.abydreadbrickslab2, ItemAbyDreadbrickSlab.class, "abydreadbrickslab2");
		GameRegistry.registerBlock(ACBlocks.liquid_antimatter, "antiwater");
		GameRegistry.registerBlock(ACBlocks.coralium_stone, "cstone");
		GameRegistry.registerBlock(ACBlocks.coralium_stone_brick, ItemMetadataBlock.class, "cstonebrick");
		GameRegistry.registerBlock(ACBlocks.coralium_stone_brick_fence, "cstonebrickfence");
		GameRegistry.registerBlock(ACBlocks.coralium_stone_brick_slab, ItemCstonebrickSlab.class, "cstonebrickslab1");
		GameRegistry.registerBlock(AbyssalCraft.cstonebrickslab2, ItemCstonebrickSlab.class, "cstonebrickslab2");
		GameRegistry.registerBlock(ACBlocks.coralium_stone_brick_stairs, "cstonebrickstairs");
		GameRegistry.registerBlock(ACBlocks.coralium_stone_button, "cstonebutton");
		GameRegistry.registerBlock(ACBlocks.coralium_stone_pressure_plate, "cstonepplate");
		GameRegistry.registerBlock(ACBlocks.chagaroth_altar_top, "dreadaltartop");
		GameRegistry.registerBlock(ACBlocks.chagaroth_altar_bottom, "dreadaltarbottom");
		GameRegistry.registerBlock(ACBlocks.crystallizer_idle, "crystallizer");
		GameRegistry.registerBlock(ACBlocks.crystallizer_active, "crystallizer_on");
		GameRegistry.registerBlock(ACBlocks.block_of_dreadium, ItemBlockColorName.class, "dreadiumblock");
		GameRegistry.registerBlock(ACBlocks.transmutator_idle, "transmutator");
		GameRegistry.registerBlock(ACBlocks.transmutator_active, "transmutator_on");
		GameRegistry.registerBlock(ACBlocks.dreadguard_spawner, "dreadguardspawner");
		GameRegistry.registerBlock(ACBlocks.chagaroth_spawner, "chagarothspawner");
		GameRegistry.registerBlock(ACBlocks.dreadlands_wood_fence, "drtfence");
		GameRegistry.registerBlock(ACBlocks.nitre_ore, "nitreore");
		GameRegistry.registerBlock(ACBlocks.abyssal_iron_ore, "abyiroore");
		GameRegistry.registerBlock(ACBlocks.abyssal_gold_ore, "abygolore");
		GameRegistry.registerBlock(ACBlocks.abyssal_diamond_ore, "abydiaore");
		GameRegistry.registerBlock(ACBlocks.abyssal_nitre_ore, "abynitore");
		GameRegistry.registerBlock(ACBlocks.abyssal_tin_ore, "abytinore");
		GameRegistry.registerBlock(ACBlocks.abyssal_copper_ore, "abycopore");
		GameRegistry.registerBlock(ACBlocks.pearlescent_coralium_ore, "abypcorore");
		GameRegistry.registerBlock(ACBlocks.liquified_coralium_ore, "abylcorore");
		GameRegistry.registerBlock(ACBlocks.solid_lava, "solidlava");
		GameRegistry.registerBlock(ACBlocks.ethaxium, ItemBlockColorName.class, "ethaxium");
		GameRegistry.registerBlock(ACBlocks.ethaxium_brick, ItemMetadataBlock.class, "ethaxiumbrick");
		GameRegistry.registerBlock(ACBlocks.ethaxium_pillar, ItemBlockColorName.class, "ethaxiumpillar");
		GameRegistry.registerBlock(ACBlocks.ethaxium_brick_stairs, ItemBlockColorName.class, "ethaxiumbrickstairs");
		GameRegistry.registerBlock(ACBlocks.ethaxium_brick_slab, ItemEthaxiumSlab.class, "ethaxiumbrickslab1");
		GameRegistry.registerBlock(AbyssalCraft.ethaxiumslab2, ItemEthaxiumSlab.class, "ethaxiumbrickslab2");
		GameRegistry.registerBlock(ACBlocks.ethaxium_brick_fence, ItemBlockColorName.class, "ethaxiumfence");
		GameRegistry.registerBlock(ACBlocks.block_of_ethaxium, ItemBlockColorName.class, "ethaxiumblock");
		GameRegistry.registerBlock(ACBlocks.omothol_stone, "omotholstone");
		GameRegistry.registerBlock(ACBlocks.omothol_gateway, "omotholportal");
		GameRegistry.registerBlock(ACBlocks.omothol_fire, "omotholfire");
		GameRegistry.registerBlock(ACBlocks.engraver, "engraver");
		GameRegistry.registerBlock(AbyssalCraft.house, "engraver_on");
		GameRegistry.registerBlock(ACBlocks.materializer, "materializer");
		GameRegistry.registerBlock(ACBlocks.dark_ethaxium_brick, ItemMetadataBlock.class, "darkethaxiumbrick");
		GameRegistry.registerBlock(ACBlocks.dark_ethaxium_pillar, ItemBlockColorName.class, "darkethaxiumpillar");
		GameRegistry.registerBlock(ACBlocks.dark_ethaxium_brick_stairs, ItemBlockColorName.class, "darkethaxiumbrickstairs");
		GameRegistry.registerBlock(ACBlocks.dark_ethaxium_brick_slab, ItemDarkEthaxiumSlab.class, "darkethaxiumbrickslab1");
		GameRegistry.registerBlock(AbyssalCraft.darkethaxiumslab2, ItemDarkEthaxiumSlab.class, "darkethaxiumbrickslab2");
		GameRegistry.registerBlock(ACBlocks.dark_ethaxium_brick_fence, ItemBlockColorName.class, "darkethaxiumbrickfence");
		GameRegistry.registerBlock(ACBlocks.ritual_altar, ItemRitualBlock.class, "ritualaltar");
		GameRegistry.registerBlock(ACBlocks.ritual_pedestal, ItemRitualBlock.class, "ritualpedestal");
		GameRegistry.registerBlock(ACBlocks.shoggoth_ooze, "shoggothblock");
		GameRegistry.registerBlock(ACBlocks.cthulhu_statue, "cthulhustatue");
		GameRegistry.registerBlock(ACBlocks.hastur_statue, "hasturstatue");
		GameRegistry.registerBlock(ACBlocks.jzahar_statue, "jzaharstatue");
		GameRegistry.registerBlock(ACBlocks.azathoth_statue, "azathothstatue");
		GameRegistry.registerBlock(ACBlocks.nyarlathotep_statue, "nyarlathotepstatue");
		GameRegistry.registerBlock(ACBlocks.yog_sothoth_statue, "yogsothothstatue");
		GameRegistry.registerBlock(ACBlocks.shub_niggurath_statue, "shubniggurathstatue");
		GameRegistry.registerBlock(ACBlocks.monolith_stone, "monolithstone");
		GameRegistry.registerBlock(ACBlocks.shoggoth_biomass, "shoggothbiomass");
		GameRegistry.registerBlock(ACBlocks.energy_pedestal, ItemPEContainerBlock.class, "energypedestal");
		GameRegistry.registerBlock(ACBlocks.monolith_pillar, "monolithpillar");
		GameRegistry.registerBlock(ACBlocks.sacrificial_altar, ItemPEContainerBlock.class, "sacrificialaltar");
		GameRegistry.registerBlock(ACBlocks.tiered_energy_pedestal, ItemMetadataPEContainerBlock.class, "tieredenergypedestal");
		GameRegistry.registerBlock(ACBlocks.tiered_sacrificial_altar, ItemMetadataPEContainerBlock.class, "tieredsacrificialaltar");
		GameRegistry.registerBlock(ACBlocks.jzahar_spawner, "jzaharspawner");
		GameRegistry.registerBlock(ACBlocks.minion_of_the_gatekeeper_spawner, "gatekeeperminionspawner");
		GameRegistry.registerBlock(ACBlocks.mimic_fire, "fire");
		GameRegistry.registerBlock(ACBlocks.decorative_cthulhu_statue, ItemDecorativeStatueBlock.class, "decorativecthulhustatue");
		GameRegistry.registerBlock(ACBlocks.decorative_hastur_statue, ItemDecorativeStatueBlock.class, "decorativehasturstatue");
		GameRegistry.registerBlock(ACBlocks.decorative_jzahar_statue, ItemDecorativeStatueBlock.class, "decorativejzaharstatue");
		GameRegistry.registerBlock(ACBlocks.decorative_azathoth_statue, ItemDecorativeStatueBlock.class, "decorativeazathothstatue");
		GameRegistry.registerBlock(ACBlocks.decorative_nyarlathotep_statue, ItemDecorativeStatueBlock.class, "decorativenyarlathotepstatue");
		GameRegistry.registerBlock(ACBlocks.decorative_yog_sothoth_statue, ItemDecorativeStatueBlock.class, "decorativeyogsothothstatue");
		GameRegistry.registerBlock(ACBlocks.decorative_shub_niggurath_statue, ItemDecorativeStatueBlock.class, "decorativeshubniggurathstatue");
		GameRegistry.registerBlock(ACBlocks.crystal_cluster, ItemCrystalClusterBlock.class, "crystalcluster");
		GameRegistry.registerBlock(ACBlocks.energy_collector, ItemPEContainerBlock.class, "energycollector");
		GameRegistry.registerBlock(ACBlocks.energy_relay, ItemPEContainerBlock.class, "energyrelay");
		GameRegistry.registerBlock(ACBlocks.energy_container, ItemPEContainerBlock.class, "energycontainer");
		GameRegistry.registerBlock(ACBlocks.tiered_energy_collector, ItemTieredEnergyCollectorBlock.class, "tieredenergycollector");
		GameRegistry.registerBlock(ACBlocks.overworld_energy_relay, ItemPEContainerBlock.class, "owenergyrelay");
		GameRegistry.registerBlock(ACBlocks.abyssal_wasteland_energy_relay, ItemPEContainerBlock.class, "awenergyrelay");
		GameRegistry.registerBlock(ACBlocks.dreadlands_energy_relay, ItemPEContainerBlock.class, "dlenergyrelay");
		GameRegistry.registerBlock(ACBlocks.omothol_energy_relay, ItemPEContainerBlock.class, "omtenergyrelay");
		GameRegistry.registerBlock(ACBlocks.tiered_energy_container, ItemTieredEnergyContainerBlock.class, "tieredenergycontainer");

		Blocks.fire.setFireInfo(ACBlocks.darklands_oak_planks, 5, 20);
		Blocks.fire.setFireInfo(AbyssalCraft.DLTslab2, 5, 20);
		Blocks.fire.setFireInfo(ACBlocks.darklands_oak_slab, 5, 20);
		Blocks.fire.setFireInfo(ACBlocks.darklands_oak_fence, 5, 20);
		Blocks.fire.setFireInfo(ACBlocks.darklands_oak_stairs, 5, 20);
		Blocks.fire.setFireInfo(ACBlocks.darklands_oak_wood, 5, 5);
		Blocks.fire.setFireInfo(ACBlocks.darklands_oak_leaves, 30, 60);

		Blocks.fire.setFireInfo(ACBlocks.dreadlands_planks, 5, 20);
		Blocks.fire.setFireInfo(ACBlocks.dreadlands_wood_fence, 5, 20);
		Blocks.fire.setFireInfo(ACBlocks.dreadlands_log, 5, 5);
		Blocks.fire.setFireInfo(ACBlocks.dreadlands_leaves, 30, 60);
	}

	@Override
	public void init(FMLInitializationEvent event) {
		AbyssalCraftAPI.addCrystal(new ItemStack(ACBlocks.crystal_cluster, 1, OreDictionary.WILDCARD_VALUE));
	}

	@Override
	public void postInit(FMLPostInitializationEvent event) {
		((BlockCLiquid) ACBlocks.liquid_coralium).addBlocks();
	}
}
